// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface CreateIndexResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.CreateIndexResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string snapshot_id = 1;</code>
   * @return The snapshotId.
   */
  java.lang.String getSnapshotId();
  /**
   * <code>string snapshot_id = 1;</code>
   * @return The bytes for snapshotId.
   */
  com.google.protobuf.ByteString
      getSnapshotIdBytes();

  /**
   * <code>string indexed_at = 2;</code>
   * @return The indexedAt.
   */
  java.lang.String getIndexedAt();
  /**
   * <code>string indexed_at = 2;</code>
   * @return The bytes for indexedAt.
   */
  com.google.protobuf.ByteString
      getIndexedAtBytes();

  /**
   * <code>int32 file_count = 3;</code>
   * @return The fileCount.
   */
  int getFileCount();

  /**
   * <code>int32 unit_count = 4;</code>
   * @return The unitCount.
   */
  int getUnitCount();

  /**
   * <code>string repo_map_json = 5;</code>
   * @return The repoMapJson.
   */
  java.lang.String getRepoMapJson();
  /**
   * <code>string repo_map_json = 5;</code>
   * @return The bytes for repoMapJson.
   */
  com.google.protobuf.ByteString
      getRepoMapJsonBytes();

  /**
   * <code>string index_lifecycle_json = 6;</code>
   * @return The indexLifecycleJson.
   */
  java.lang.String getIndexLifecycleJson();
  /**
   * <code>string index_lifecycle_json = 6;</code>
   * @return The bytes for indexLifecycleJson.
   */
  com.google.protobuf.ByteString
      getIndexLifecycleJsonBytes();

  /**
   * <pre>
   * plans/018 Stage 6.4. JSON-encoded provider summary, carried the same way
   * HealthResponse carries capabilities_json. Empty when the build ran no
   * provider pipeline, which keeps it additive: a client that never asks reads
   * an empty string exactly as it read a missing field before.
   * </pre>
   *
   * <code>string provider_summary_json = 7;</code>
   * @return The providerSummaryJson.
   */
  java.lang.String getProviderSummaryJson();
  /**
   * <pre>
   * plans/018 Stage 6.4. JSON-encoded provider summary, carried the same way
   * HealthResponse carries capabilities_json. Empty when the build ran no
   * provider pipeline, which keeps it additive: a client that never asks reads
   * an empty string exactly as it read a missing field before.
   * </pre>
   *
   * <code>string provider_summary_json = 7;</code>
   * @return The bytes for providerSummaryJson.
   */
  com.google.protobuf.ByteString
      getProviderSummaryJsonBytes();
}
