// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface ExpandContextResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.ExpandContextResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string expansion_result_json = 1;</code>
   * @return The expansionResultJson.
   */
  java.lang.String getExpansionResultJson();
  /**
   * <code>string expansion_result_json = 1;</code>
   * @return The bytes for expansionResultJson.
   */
  com.google.protobuf.ByteString
      getExpansionResultJsonBytes();
}
