// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface FetchContextDetailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.FetchContextDetailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string root_path = 1;</code>
   * @return The rootPath.
   */
  java.lang.String getRootPath();
  /**
   * <code>string root_path = 1;</code>
   * @return The bytes for rootPath.
   */
  com.google.protobuf.ByteString
      getRootPathBytes();

  /**
   * <code>repeated string paths = 2;</code>
   * @return A list containing the paths.
   */
  java.util.List<java.lang.String>
      getPathsList();
  /**
   * <code>repeated string paths = 2;</code>
   * @return The count of paths.
   */
  int getPathsCount();
  /**
   * <code>repeated string paths = 2;</code>
   * @param index The index of the element to return.
   * @return The paths at the given index.
   */
  java.lang.String getPaths(int index);
  /**
   * <code>repeated string paths = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the paths at the given index.
   */
  com.google.protobuf.ByteString
      getPathsBytes(int index);

  /**
   * <code>string parser_opts_json = 3;</code>
   * @return The parserOptsJson.
   */
  java.lang.String getParserOptsJson();
  /**
   * <code>string parser_opts_json = 3;</code>
   * @return The bytes for parserOptsJson.
   */
  com.google.protobuf.ByteString
      getParserOptsJsonBytes();

  /**
   * <code>string selection_id = 4;</code>
   * @return The selectionId.
   */
  java.lang.String getSelectionId();
  /**
   * <code>string selection_id = 4;</code>
   * @return The bytes for selectionId.
   */
  com.google.protobuf.ByteString
      getSelectionIdBytes();

  /**
   * <code>string snapshot_id = 5;</code>
   * @return The snapshotId.
   */
  java.lang.String getSnapshotId();
  /**
   * <code>string snapshot_id = 5;</code>
   * @return The bytes for snapshotId.
   */
  com.google.protobuf.ByteString
      getSnapshotIdBytes();

  /**
   * <code>repeated string unit_ids = 6;</code>
   * @return A list containing the unitIds.
   */
  java.util.List<java.lang.String>
      getUnitIdsList();
  /**
   * <code>repeated string unit_ids = 6;</code>
   * @return The count of unitIds.
   */
  int getUnitIdsCount();
  /**
   * <code>repeated string unit_ids = 6;</code>
   * @param index The index of the element to return.
   * @return The unitIds at the given index.
   */
  java.lang.String getUnitIds(int index);
  /**
   * <code>repeated string unit_ids = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the unitIds at the given index.
   */
  com.google.protobuf.ByteString
      getUnitIdsBytes(int index);

  /**
   * <code>string detail_level = 7;</code>
   * @return The detailLevel.
   */
  java.lang.String getDetailLevel();
  /**
   * <code>string detail_level = 7;</code>
   * @return The bytes for detailLevel.
   */
  com.google.protobuf.ByteString
      getDetailLevelBytes();

  /**
   * <code>string language_policy_json = 8;</code>
   * @return The languagePolicyJson.
   */
  java.lang.String getLanguagePolicyJson();
  /**
   * <code>string language_policy_json = 8;</code>
   * @return The bytes for languagePolicyJson.
   */
  com.google.protobuf.ByteString
      getLanguagePolicyJsonBytes();
}
