// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface FetchContextDetailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.FetchContextDetailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string detail_result_json = 1;</code>
   * @return The detailResultJson.
   */
  java.lang.String getDetailResultJson();
  /**
   * <code>string detail_result_json = 1;</code>
   * @return The bytes for detailResultJson.
   */
  com.google.protobuf.ByteString
      getDetailResultJsonBytes();
}
