// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface HealthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.HealthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string service = 2;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 2;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string capabilities_json = 3;</code>
   * @return The capabilitiesJson.
   */
  java.lang.String getCapabilitiesJson();
  /**
   * <code>string capabilities_json = 3;</code>
   * @return The bytes for capabilitiesJson.
   */
  com.google.protobuf.ByteString
      getCapabilitiesJsonBytes();
}
