// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface HealthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.HealthRequest)
    com.google.protobuf.MessageOrBuilder {
}
