// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

/**
 * Protobuf type {@code semidx.runtime.grpc.v1.LiteralFileSliceResponse}
 */
public final class LiteralFileSliceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:semidx.runtime.grpc.v1.LiteralFileSliceResponse)
    LiteralFileSliceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LiteralFileSliceResponse.newBuilder() to construct.
  private LiteralFileSliceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LiteralFileSliceResponse() {
    literalSliceResultJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LiteralFileSliceResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            semidx.runtime.grpc.v1.LiteralFileSliceResponse.class, semidx.runtime.grpc.v1.LiteralFileSliceResponse.Builder.class);
  }

  public static final int LITERAL_SLICE_RESULT_JSON_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object literalSliceResultJson_ = "";
  /**
   * <code>string literal_slice_result_json = 1;</code>
   * @return The literalSliceResultJson.
   */
  @java.lang.Override
  public java.lang.String getLiteralSliceResultJson() {
    java.lang.Object ref = literalSliceResultJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      literalSliceResultJson_ = s;
      return s;
    }
  }
  /**
   * <code>string literal_slice_result_json = 1;</code>
   * @return The bytes for literalSliceResultJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLiteralSliceResultJsonBytes() {
    java.lang.Object ref = literalSliceResultJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      literalSliceResultJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(literalSliceResultJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, literalSliceResultJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(literalSliceResultJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, literalSliceResultJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof semidx.runtime.grpc.v1.LiteralFileSliceResponse)) {
      return super.equals(obj);
    }
    semidx.runtime.grpc.v1.LiteralFileSliceResponse other = (semidx.runtime.grpc.v1.LiteralFileSliceResponse) obj;

    if (!getLiteralSliceResultJson()
        .equals(other.getLiteralSliceResultJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LITERAL_SLICE_RESULT_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getLiteralSliceResultJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(semidx.runtime.grpc.v1.LiteralFileSliceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code semidx.runtime.grpc.v1.LiteralFileSliceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:semidx.runtime.grpc.v1.LiteralFileSliceResponse)
      semidx.runtime.grpc.v1.LiteralFileSliceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              semidx.runtime.grpc.v1.LiteralFileSliceResponse.class, semidx.runtime.grpc.v1.LiteralFileSliceResponse.Builder.class);
    }

    // Construct using semidx.runtime.grpc.v1.LiteralFileSliceResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      literalSliceResultJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_descriptor;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.LiteralFileSliceResponse getDefaultInstanceForType() {
      return semidx.runtime.grpc.v1.LiteralFileSliceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.LiteralFileSliceResponse build() {
      semidx.runtime.grpc.v1.LiteralFileSliceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.LiteralFileSliceResponse buildPartial() {
      semidx.runtime.grpc.v1.LiteralFileSliceResponse result = new semidx.runtime.grpc.v1.LiteralFileSliceResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(semidx.runtime.grpc.v1.LiteralFileSliceResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.literalSliceResultJson_ = literalSliceResultJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof semidx.runtime.grpc.v1.LiteralFileSliceResponse) {
        return mergeFrom((semidx.runtime.grpc.v1.LiteralFileSliceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(semidx.runtime.grpc.v1.LiteralFileSliceResponse other) {
      if (other == semidx.runtime.grpc.v1.LiteralFileSliceResponse.getDefaultInstance()) return this;
      if (!other.getLiteralSliceResultJson().isEmpty()) {
        literalSliceResultJson_ = other.literalSliceResultJson_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              literalSliceResultJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object literalSliceResultJson_ = "";
    /**
     * <code>string literal_slice_result_json = 1;</code>
     * @return The literalSliceResultJson.
     */
    public java.lang.String getLiteralSliceResultJson() {
      java.lang.Object ref = literalSliceResultJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        literalSliceResultJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string literal_slice_result_json = 1;</code>
     * @return The bytes for literalSliceResultJson.
     */
    public com.google.protobuf.ByteString
        getLiteralSliceResultJsonBytes() {
      java.lang.Object ref = literalSliceResultJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        literalSliceResultJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string literal_slice_result_json = 1;</code>
     * @param value The literalSliceResultJson to set.
     * @return This builder for chaining.
     */
    public Builder setLiteralSliceResultJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      literalSliceResultJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string literal_slice_result_json = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLiteralSliceResultJson() {
      literalSliceResultJson_ = getDefaultInstance().getLiteralSliceResultJson();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string literal_slice_result_json = 1;</code>
     * @param value The bytes for literalSliceResultJson to set.
     * @return This builder for chaining.
     */
    public Builder setLiteralSliceResultJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      literalSliceResultJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:semidx.runtime.grpc.v1.LiteralFileSliceResponse)
  }

  // @@protoc_insertion_point(class_scope:semidx.runtime.grpc.v1.LiteralFileSliceResponse)
  private static final semidx.runtime.grpc.v1.LiteralFileSliceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new semidx.runtime.grpc.v1.LiteralFileSliceResponse();
  }

  public static semidx.runtime.grpc.v1.LiteralFileSliceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LiteralFileSliceResponse>
      PARSER = new com.google.protobuf.AbstractParser<LiteralFileSliceResponse>() {
    @java.lang.Override
    public LiteralFileSliceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LiteralFileSliceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LiteralFileSliceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public semidx.runtime.grpc.v1.LiteralFileSliceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

