// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface LiteralFileSliceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.LiteralFileSliceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string literal_slice_result_json = 1;</code>
   * @return The literalSliceResultJson.
   */
  java.lang.String getLiteralSliceResultJson();
  /**
   * <code>string literal_slice_result_json = 1;</code>
   * @return The bytes for literalSliceResultJson.
   */
  com.google.protobuf.ByteString
      getLiteralSliceResultJsonBytes();
}
