// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface ResolveContextRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.ResolveContextRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string root_path = 1;</code>
   * @return The rootPath.
   */
  java.lang.String getRootPath();
  /**
   * <code>string root_path = 1;</code>
   * @return The bytes for rootPath.
   */
  com.google.protobuf.ByteString
      getRootPathBytes();

  /**
   * <code>repeated string paths = 2;</code>
   * @return A list containing the paths.
   */
  java.util.List<java.lang.String>
      getPathsList();
  /**
   * <code>repeated string paths = 2;</code>
   * @return The count of paths.
   */
  int getPathsCount();
  /**
   * <code>repeated string paths = 2;</code>
   * @param index The index of the element to return.
   * @return The paths at the given index.
   */
  java.lang.String getPaths(int index);
  /**
   * <code>repeated string paths = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the paths at the given index.
   */
  com.google.protobuf.ByteString
      getPathsBytes(int index);

  /**
   * <code>string parser_opts_json = 3;</code>
   * @return The parserOptsJson.
   */
  java.lang.String getParserOptsJson();
  /**
   * <code>string parser_opts_json = 3;</code>
   * @return The bytes for parserOptsJson.
   */
  com.google.protobuf.ByteString
      getParserOptsJsonBytes();

  /**
   * <code>string query_json = 4;</code>
   * @return The queryJson.
   */
  java.lang.String getQueryJson();
  /**
   * <code>string query_json = 4;</code>
   * @return The bytes for queryJson.
   */
  com.google.protobuf.ByteString
      getQueryJsonBytes();

  /**
   * <code>string retrieval_policy_json = 5;</code>
   * @return The retrievalPolicyJson.
   */
  java.lang.String getRetrievalPolicyJson();
  /**
   * <code>string retrieval_policy_json = 5;</code>
   * @return The bytes for retrievalPolicyJson.
   */
  com.google.protobuf.ByteString
      getRetrievalPolicyJsonBytes();

  /**
   * <code>string language_policy_json = 6;</code>
   * @return The languagePolicyJson.
   */
  java.lang.String getLanguagePolicyJson();
  /**
   * <code>string language_policy_json = 6;</code>
   * @return The bytes for languagePolicyJson.
   */
  com.google.protobuf.ByteString
      getLanguagePolicyJsonBytes();
}
