// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface ResolveContextResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.ResolveContextResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string selection_result_json = 1;</code>
   * @return The selectionResultJson.
   */
  java.lang.String getSelectionResultJson();
  /**
   * <code>string selection_result_json = 1;</code>
   * @return The bytes for selectionResultJson.
   */
  com.google.protobuf.ByteString
      getSelectionResultJsonBytes();
}
