// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

/**
 * Protobuf type {@code semidx.runtime.grpc.v1.ResolveContextRequest}
 */
public final class ResolveContextRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:semidx.runtime.grpc.v1.ResolveContextRequest)
    ResolveContextRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResolveContextRequest.newBuilder() to construct.
  private ResolveContextRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResolveContextRequest() {
    rootPath_ = "";
    paths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    parserOptsJson_ = "";
    queryJson_ = "";
    retrievalPolicyJson_ = "";
    languagePolicyJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResolveContextRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            semidx.runtime.grpc.v1.ResolveContextRequest.class, semidx.runtime.grpc.v1.ResolveContextRequest.Builder.class);
  }

  public static final int ROOT_PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rootPath_ = "";
  /**
   * <code>string root_path = 1;</code>
   * @return The rootPath.
   */
  @java.lang.Override
  public java.lang.String getRootPath() {
    java.lang.Object ref = rootPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rootPath_ = s;
      return s;
    }
  }
  /**
   * <code>string root_path = 1;</code>
   * @return The bytes for rootPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRootPathBytes() {
    java.lang.Object ref = rootPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rootPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATHS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList paths_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string paths = 2;</code>
   * @return A list containing the paths.
   */
  public com.google.protobuf.ProtocolStringList
      getPathsList() {
    return paths_;
  }
  /**
   * <code>repeated string paths = 2;</code>
   * @return The count of paths.
   */
  public int getPathsCount() {
    return paths_.size();
  }
  /**
   * <code>repeated string paths = 2;</code>
   * @param index The index of the element to return.
   * @return The paths at the given index.
   */
  public java.lang.String getPaths(int index) {
    return paths_.get(index);
  }
  /**
   * <code>repeated string paths = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the paths at the given index.
   */
  public com.google.protobuf.ByteString
      getPathsBytes(int index) {
    return paths_.getByteString(index);
  }

  public static final int PARSER_OPTS_JSON_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parserOptsJson_ = "";
  /**
   * <code>string parser_opts_json = 3;</code>
   * @return The parserOptsJson.
   */
  @java.lang.Override
  public java.lang.String getParserOptsJson() {
    java.lang.Object ref = parserOptsJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parserOptsJson_ = s;
      return s;
    }
  }
  /**
   * <code>string parser_opts_json = 3;</code>
   * @return The bytes for parserOptsJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParserOptsJsonBytes() {
    java.lang.Object ref = parserOptsJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parserOptsJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERY_JSON_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object queryJson_ = "";
  /**
   * <code>string query_json = 4;</code>
   * @return The queryJson.
   */
  @java.lang.Override
  public java.lang.String getQueryJson() {
    java.lang.Object ref = queryJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      queryJson_ = s;
      return s;
    }
  }
  /**
   * <code>string query_json = 4;</code>
   * @return The bytes for queryJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueryJsonBytes() {
    java.lang.Object ref = queryJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queryJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETRIEVAL_POLICY_JSON_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object retrievalPolicyJson_ = "";
  /**
   * <code>string retrieval_policy_json = 5;</code>
   * @return The retrievalPolicyJson.
   */
  @java.lang.Override
  public java.lang.String getRetrievalPolicyJson() {
    java.lang.Object ref = retrievalPolicyJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      retrievalPolicyJson_ = s;
      return s;
    }
  }
  /**
   * <code>string retrieval_policy_json = 5;</code>
   * @return The bytes for retrievalPolicyJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRetrievalPolicyJsonBytes() {
    java.lang.Object ref = retrievalPolicyJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      retrievalPolicyJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGE_POLICY_JSON_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object languagePolicyJson_ = "";
  /**
   * <code>string language_policy_json = 6;</code>
   * @return The languagePolicyJson.
   */
  @java.lang.Override
  public java.lang.String getLanguagePolicyJson() {
    java.lang.Object ref = languagePolicyJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languagePolicyJson_ = s;
      return s;
    }
  }
  /**
   * <code>string language_policy_json = 6;</code>
   * @return The bytes for languagePolicyJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguagePolicyJsonBytes() {
    java.lang.Object ref = languagePolicyJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languagePolicyJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootPath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rootPath_);
    }
    for (int i = 0; i < paths_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, paths_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parserOptsJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parserOptsJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(queryJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, queryJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(retrievalPolicyJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, retrievalPolicyJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languagePolicyJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, languagePolicyJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootPath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rootPath_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < paths_.size(); i++) {
        dataSize += computeStringSizeNoTag(paths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPathsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parserOptsJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, parserOptsJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(queryJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, queryJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(retrievalPolicyJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, retrievalPolicyJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languagePolicyJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, languagePolicyJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof semidx.runtime.grpc.v1.ResolveContextRequest)) {
      return super.equals(obj);
    }
    semidx.runtime.grpc.v1.ResolveContextRequest other = (semidx.runtime.grpc.v1.ResolveContextRequest) obj;

    if (!getRootPath()
        .equals(other.getRootPath())) return false;
    if (!getPathsList()
        .equals(other.getPathsList())) return false;
    if (!getParserOptsJson()
        .equals(other.getParserOptsJson())) return false;
    if (!getQueryJson()
        .equals(other.getQueryJson())) return false;
    if (!getRetrievalPolicyJson()
        .equals(other.getRetrievalPolicyJson())) return false;
    if (!getLanguagePolicyJson()
        .equals(other.getLanguagePolicyJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOT_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getRootPath().hashCode();
    if (getPathsCount() > 0) {
      hash = (37 * hash) + PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getPathsList().hashCode();
    }
    hash = (37 * hash) + PARSER_OPTS_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getParserOptsJson().hashCode();
    hash = (37 * hash) + QUERY_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getQueryJson().hashCode();
    hash = (37 * hash) + RETRIEVAL_POLICY_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getRetrievalPolicyJson().hashCode();
    hash = (37 * hash) + LANGUAGE_POLICY_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getLanguagePolicyJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static semidx.runtime.grpc.v1.ResolveContextRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static semidx.runtime.grpc.v1.ResolveContextRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.ResolveContextRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(semidx.runtime.grpc.v1.ResolveContextRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code semidx.runtime.grpc.v1.ResolveContextRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:semidx.runtime.grpc.v1.ResolveContextRequest)
      semidx.runtime.grpc.v1.ResolveContextRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              semidx.runtime.grpc.v1.ResolveContextRequest.class, semidx.runtime.grpc.v1.ResolveContextRequest.Builder.class);
    }

    // Construct using semidx.runtime.grpc.v1.ResolveContextRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rootPath_ = "";
      paths_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      parserOptsJson_ = "";
      queryJson_ = "";
      retrievalPolicyJson_ = "";
      languagePolicyJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_descriptor;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.ResolveContextRequest getDefaultInstanceForType() {
      return semidx.runtime.grpc.v1.ResolveContextRequest.getDefaultInstance();
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.ResolveContextRequest build() {
      semidx.runtime.grpc.v1.ResolveContextRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.ResolveContextRequest buildPartial() {
      semidx.runtime.grpc.v1.ResolveContextRequest result = new semidx.runtime.grpc.v1.ResolveContextRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(semidx.runtime.grpc.v1.ResolveContextRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rootPath_ = rootPath_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        paths_.makeImmutable();
        result.paths_ = paths_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.parserOptsJson_ = parserOptsJson_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.queryJson_ = queryJson_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.retrievalPolicyJson_ = retrievalPolicyJson_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.languagePolicyJson_ = languagePolicyJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof semidx.runtime.grpc.v1.ResolveContextRequest) {
        return mergeFrom((semidx.runtime.grpc.v1.ResolveContextRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(semidx.runtime.grpc.v1.ResolveContextRequest other) {
      if (other == semidx.runtime.grpc.v1.ResolveContextRequest.getDefaultInstance()) return this;
      if (!other.getRootPath().isEmpty()) {
        rootPath_ = other.rootPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.paths_.isEmpty()) {
        if (paths_.isEmpty()) {
          paths_ = other.paths_;
          bitField0_ |= 0x00000002;
        } else {
          ensurePathsIsMutable();
          paths_.addAll(other.paths_);
        }
        onChanged();
      }
      if (!other.getParserOptsJson().isEmpty()) {
        parserOptsJson_ = other.parserOptsJson_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getQueryJson().isEmpty()) {
        queryJson_ = other.queryJson_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getRetrievalPolicyJson().isEmpty()) {
        retrievalPolicyJson_ = other.retrievalPolicyJson_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getLanguagePolicyJson().isEmpty()) {
        languagePolicyJson_ = other.languagePolicyJson_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rootPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensurePathsIsMutable();
              paths_.add(s);
              break;
            } // case 18
            case 26: {
              parserOptsJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              queryJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              retrievalPolicyJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              languagePolicyJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object rootPath_ = "";
    /**
     * <code>string root_path = 1;</code>
     * @return The rootPath.
     */
    public java.lang.String getRootPath() {
      java.lang.Object ref = rootPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rootPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string root_path = 1;</code>
     * @return The bytes for rootPath.
     */
    public com.google.protobuf.ByteString
        getRootPathBytes() {
      java.lang.Object ref = rootPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rootPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string root_path = 1;</code>
     * @param value The rootPath to set.
     * @return This builder for chaining.
     */
    public Builder setRootPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rootPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string root_path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRootPath() {
      rootPath_ = getDefaultInstance().getRootPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string root_path = 1;</code>
     * @param value The bytes for rootPath to set.
     * @return This builder for chaining.
     */
    public Builder setRootPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rootPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList paths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensurePathsIsMutable() {
      if (!paths_.isModifiable()) {
        paths_ = new com.google.protobuf.LazyStringArrayList(paths_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @return A list containing the paths.
     */
    public com.google.protobuf.ProtocolStringList
        getPathsList() {
      paths_.makeImmutable();
      return paths_;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @return The count of paths.
     */
    public int getPathsCount() {
      return paths_.size();
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param index The index of the element to return.
     * @return The paths at the given index.
     */
    public java.lang.String getPaths(int index) {
      return paths_.get(index);
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paths at the given index.
     */
    public com.google.protobuf.ByteString
        getPathsBytes(int index) {
      return paths_.getByteString(index);
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param index The index to set the value at.
     * @param value The paths to set.
     * @return This builder for chaining.
     */
    public Builder setPaths(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePathsIsMutable();
      paths_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param value The paths to add.
     * @return This builder for chaining.
     */
    public Builder addPaths(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePathsIsMutable();
      paths_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param values The paths to add.
     * @return This builder for chaining.
     */
    public Builder addAllPaths(
        java.lang.Iterable<java.lang.String> values) {
      ensurePathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, paths_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaths() {
      paths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param value The bytes of the paths to add.
     * @return This builder for chaining.
     */
    public Builder addPathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensurePathsIsMutable();
      paths_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object parserOptsJson_ = "";
    /**
     * <code>string parser_opts_json = 3;</code>
     * @return The parserOptsJson.
     */
    public java.lang.String getParserOptsJson() {
      java.lang.Object ref = parserOptsJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parserOptsJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parser_opts_json = 3;</code>
     * @return The bytes for parserOptsJson.
     */
    public com.google.protobuf.ByteString
        getParserOptsJsonBytes() {
      java.lang.Object ref = parserOptsJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parserOptsJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parser_opts_json = 3;</code>
     * @param value The parserOptsJson to set.
     * @return This builder for chaining.
     */
    public Builder setParserOptsJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parserOptsJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string parser_opts_json = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParserOptsJson() {
      parserOptsJson_ = getDefaultInstance().getParserOptsJson();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string parser_opts_json = 3;</code>
     * @param value The bytes for parserOptsJson to set.
     * @return This builder for chaining.
     */
    public Builder setParserOptsJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parserOptsJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object queryJson_ = "";
    /**
     * <code>string query_json = 4;</code>
     * @return The queryJson.
     */
    public java.lang.String getQueryJson() {
      java.lang.Object ref = queryJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queryJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string query_json = 4;</code>
     * @return The bytes for queryJson.
     */
    public com.google.protobuf.ByteString
        getQueryJsonBytes() {
      java.lang.Object ref = queryJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queryJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string query_json = 4;</code>
     * @param value The queryJson to set.
     * @return This builder for chaining.
     */
    public Builder setQueryJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      queryJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string query_json = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryJson() {
      queryJson_ = getDefaultInstance().getQueryJson();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string query_json = 4;</code>
     * @param value The bytes for queryJson to set.
     * @return This builder for chaining.
     */
    public Builder setQueryJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      queryJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object retrievalPolicyJson_ = "";
    /**
     * <code>string retrieval_policy_json = 5;</code>
     * @return The retrievalPolicyJson.
     */
    public java.lang.String getRetrievalPolicyJson() {
      java.lang.Object ref = retrievalPolicyJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        retrievalPolicyJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string retrieval_policy_json = 5;</code>
     * @return The bytes for retrievalPolicyJson.
     */
    public com.google.protobuf.ByteString
        getRetrievalPolicyJsonBytes() {
      java.lang.Object ref = retrievalPolicyJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retrievalPolicyJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string retrieval_policy_json = 5;</code>
     * @param value The retrievalPolicyJson to set.
     * @return This builder for chaining.
     */
    public Builder setRetrievalPolicyJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      retrievalPolicyJson_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string retrieval_policy_json = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetrievalPolicyJson() {
      retrievalPolicyJson_ = getDefaultInstance().getRetrievalPolicyJson();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string retrieval_policy_json = 5;</code>
     * @param value The bytes for retrievalPolicyJson to set.
     * @return This builder for chaining.
     */
    public Builder setRetrievalPolicyJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      retrievalPolicyJson_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object languagePolicyJson_ = "";
    /**
     * <code>string language_policy_json = 6;</code>
     * @return The languagePolicyJson.
     */
    public java.lang.String getLanguagePolicyJson() {
      java.lang.Object ref = languagePolicyJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languagePolicyJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string language_policy_json = 6;</code>
     * @return The bytes for languagePolicyJson.
     */
    public com.google.protobuf.ByteString
        getLanguagePolicyJsonBytes() {
      java.lang.Object ref = languagePolicyJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languagePolicyJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string language_policy_json = 6;</code>
     * @param value The languagePolicyJson to set.
     * @return This builder for chaining.
     */
    public Builder setLanguagePolicyJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      languagePolicyJson_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string language_policy_json = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguagePolicyJson() {
      languagePolicyJson_ = getDefaultInstance().getLanguagePolicyJson();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string language_policy_json = 6;</code>
     * @param value The bytes for languagePolicyJson to set.
     * @return This builder for chaining.
     */
    public Builder setLanguagePolicyJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      languagePolicyJson_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:semidx.runtime.grpc.v1.ResolveContextRequest)
  }

  // @@protoc_insertion_point(class_scope:semidx.runtime.grpc.v1.ResolveContextRequest)
  private static final semidx.runtime.grpc.v1.ResolveContextRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new semidx.runtime.grpc.v1.ResolveContextRequest();
  }

  public static semidx.runtime.grpc.v1.ResolveContextRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResolveContextRequest>
      PARSER = new com.google.protobuf.AbstractParser<ResolveContextRequest>() {
    @java.lang.Override
    public ResolveContextRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResolveContextRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResolveContextRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public semidx.runtime.grpc.v1.ResolveContextRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

