// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

/**
 * Protobuf type {@code semidx.runtime.grpc.v1.ResolveContextResponse}
 */
public final class ResolveContextResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:semidx.runtime.grpc.v1.ResolveContextResponse)
    ResolveContextResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResolveContextResponse.newBuilder() to construct.
  private ResolveContextResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResolveContextResponse() {
    selectionResultJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResolveContextResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            semidx.runtime.grpc.v1.ResolveContextResponse.class, semidx.runtime.grpc.v1.ResolveContextResponse.Builder.class);
  }

  public static final int SELECTION_RESULT_JSON_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object selectionResultJson_ = "";
  /**
   * <code>string selection_result_json = 1;</code>
   * @return The selectionResultJson.
   */
  @java.lang.Override
  public java.lang.String getSelectionResultJson() {
    java.lang.Object ref = selectionResultJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      selectionResultJson_ = s;
      return s;
    }
  }
  /**
   * <code>string selection_result_json = 1;</code>
   * @return The bytes for selectionResultJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSelectionResultJsonBytes() {
    java.lang.Object ref = selectionResultJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      selectionResultJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(selectionResultJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, selectionResultJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(selectionResultJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, selectionResultJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof semidx.runtime.grpc.v1.ResolveContextResponse)) {
      return super.equals(obj);
    }
    semidx.runtime.grpc.v1.ResolveContextResponse other = (semidx.runtime.grpc.v1.ResolveContextResponse) obj;

    if (!getSelectionResultJson()
        .equals(other.getSelectionResultJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SELECTION_RESULT_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getSelectionResultJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static semidx.runtime.grpc.v1.ResolveContextResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static semidx.runtime.grpc.v1.ResolveContextResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.ResolveContextResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(semidx.runtime.grpc.v1.ResolveContextResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code semidx.runtime.grpc.v1.ResolveContextResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:semidx.runtime.grpc.v1.ResolveContextResponse)
      semidx.runtime.grpc.v1.ResolveContextResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              semidx.runtime.grpc.v1.ResolveContextResponse.class, semidx.runtime.grpc.v1.ResolveContextResponse.Builder.class);
    }

    // Construct using semidx.runtime.grpc.v1.ResolveContextResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      selectionResultJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_descriptor;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.ResolveContextResponse getDefaultInstanceForType() {
      return semidx.runtime.grpc.v1.ResolveContextResponse.getDefaultInstance();
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.ResolveContextResponse build() {
      semidx.runtime.grpc.v1.ResolveContextResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.ResolveContextResponse buildPartial() {
      semidx.runtime.grpc.v1.ResolveContextResponse result = new semidx.runtime.grpc.v1.ResolveContextResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(semidx.runtime.grpc.v1.ResolveContextResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.selectionResultJson_ = selectionResultJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof semidx.runtime.grpc.v1.ResolveContextResponse) {
        return mergeFrom((semidx.runtime.grpc.v1.ResolveContextResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(semidx.runtime.grpc.v1.ResolveContextResponse other) {
      if (other == semidx.runtime.grpc.v1.ResolveContextResponse.getDefaultInstance()) return this;
      if (!other.getSelectionResultJson().isEmpty()) {
        selectionResultJson_ = other.selectionResultJson_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              selectionResultJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object selectionResultJson_ = "";
    /**
     * <code>string selection_result_json = 1;</code>
     * @return The selectionResultJson.
     */
    public java.lang.String getSelectionResultJson() {
      java.lang.Object ref = selectionResultJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectionResultJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string selection_result_json = 1;</code>
     * @return The bytes for selectionResultJson.
     */
    public com.google.protobuf.ByteString
        getSelectionResultJsonBytes() {
      java.lang.Object ref = selectionResultJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectionResultJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string selection_result_json = 1;</code>
     * @param value The selectionResultJson to set.
     * @return This builder for chaining.
     */
    public Builder setSelectionResultJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      selectionResultJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string selection_result_json = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelectionResultJson() {
      selectionResultJson_ = getDefaultInstance().getSelectionResultJson();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string selection_result_json = 1;</code>
     * @param value The bytes for selectionResultJson to set.
     * @return This builder for chaining.
     */
    public Builder setSelectionResultJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      selectionResultJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:semidx.runtime.grpc.v1.ResolveContextResponse)
  }

  // @@protoc_insertion_point(class_scope:semidx.runtime.grpc.v1.ResolveContextResponse)
  private static final semidx.runtime.grpc.v1.ResolveContextResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new semidx.runtime.grpc.v1.ResolveContextResponse();
  }

  public static semidx.runtime.grpc.v1.ResolveContextResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResolveContextResponse>
      PARSER = new com.google.protobuf.AbstractParser<ResolveContextResponse>() {
    @java.lang.Override
    public ResolveContextResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResolveContextResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResolveContextResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public semidx.runtime.grpc.v1.ResolveContextResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

