// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public final class RuntimeProto {
  private RuntimeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_HealthRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_HealthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_HealthResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_HealthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_CreateIndexRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_CreateIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_CreateIndexResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_CreateIndexResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_ExpandContextRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_ExpandContextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_ExpandContextResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_ExpandContextResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_FetchContextDetailRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_FetchContextDetailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_FetchContextDetailResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_FetchContextDetailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_LiteralFileSliceRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_LiteralFileSliceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_SnapshotDiffRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_SnapshotDiffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_SnapshotDiffResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_SnapshotDiffResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$semidx/runtime/grpc/v1/runtime.proto\022\026" +
      "semidx.runtime.grpc.v1\"\017\n\rHealthRequest\"" +
      "L\n\016HealthResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007ser" +
      "vice\030\002 \001(\t\022\031\n\021capabilities_json\030\003 \001(\t\"n\n" +
      "\022CreateIndexRequest\022\021\n\troot_path\030\001 \001(\t\022\r" +
      "\n\005paths\030\002 \003(\t\022\030\n\020parser_opts_json\030\003 \001(\t\022" +
      "\034\n\024language_policy_json\030\004 \001(\t\"\272\001\n\023Create" +
      "IndexResponse\022\023\n\013snapshot_id\030\001 \001(\t\022\022\n\nin" +
      "dexed_at\030\002 \001(\t\022\022\n\nfile_count\030\003 \001(\005\022\022\n\nun" +
      "it_count\030\004 \001(\005\022\025\n\rrepo_map_json\030\005 \001(\t\022\034\n" +
      "\024index_lifecycle_json\030\006 \001(\t\022\035\n\025provider_" +
      "summary_json\030\007 \001(\t\"\244\001\n\025ResolveContextReq" +
      "uest\022\021\n\troot_path\030\001 \001(\t\022\r\n\005paths\030\002 \003(\t\022\030" +
      "\n\020parser_opts_json\030\003 \001(\t\022\022\n\nquery_json\030\004" +
      " \001(\t\022\035\n\025retrieval_policy_json\030\005 \001(\t\022\034\n\024l" +
      "anguage_policy_json\030\006 \001(\t\"7\n\026ResolveCont" +
      "extResponse\022\035\n\025selection_result_json\030\001 \001" +
      "(\t\"\313\001\n\024ExpandContextRequest\022\021\n\troot_path" +
      "\030\001 \001(\t\022\r\n\005paths\030\002 \003(\t\022\030\n\020parser_opts_jso" +
      "n\030\003 \001(\t\022\024\n\014selection_id\030\004 \001(\t\022\023\n\013snapsho" +
      "t_id\030\005 \001(\t\022\020\n\010unit_ids\030\006 \003(\t\022\034\n\024include_" +
      "impact_hints\030\007 \001(\t\022\034\n\024language_policy_js" +
      "on\030\010 \001(\t\"6\n\025ExpandContextResponse\022\035\n\025exp" +
      "ansion_result_json\030\001 \001(\t\"\310\001\n\031FetchContex" +
      "tDetailRequest\022\021\n\troot_path\030\001 \001(\t\022\r\n\005pat" +
      "hs\030\002 \003(\t\022\030\n\020parser_opts_json\030\003 \001(\t\022\024\n\014se" +
      "lection_id\030\004 \001(\t\022\023\n\013snapshot_id\030\005 \001(\t\022\020\n" +
      "\010unit_ids\030\006 \003(\t\022\024\n\014detail_level\030\007 \001(\t\022\034\n" +
      "\024language_policy_json\030\010 \001(\t\"8\n\032FetchCont" +
      "extDetailResponse\022\032\n\022detail_result_json\030" +
      "\001 \001(\t\"\322\001\n\027LiteralFileSliceRequest\022\021\n\troo" +
      "t_path\030\001 \001(\t\022\r\n\005paths\030\002 \003(\t\022\030\n\020parser_op" +
      "ts_json\030\003 \001(\t\022\024\n\014selection_id\030\004 \001(\t\022\023\n\013s" +
      "napshot_id\030\005 \001(\t\022\014\n\004path\030\006 \001(\t\022\022\n\nstart_" +
      "line\030\007 \001(\005\022\020\n\010end_line\030\010 \001(\005\022\034\n\024language" +
      "_policy_json\030\t \001(\t\"=\n\030LiteralFileSliceRe" +
      "sponse\022!\n\031literal_slice_result_json\030\001 \001(" +
      "\t\"\250\001\n\023SnapshotDiffRequest\022\021\n\troot_path\030\001" +
      " \001(\t\022\r\n\005paths\030\002 \003(\t\022\030\n\020parser_opts_json\030" +
      "\003 \001(\t\022\034\n\024baseline_snapshot_id\030\004 \001(\t\022\031\n\021i" +
      "nclude_unchanged\030\005 \001(\t\022\034\n\024language_polic" +
      "y_json\030\006 \001(\t\"9\n\024SnapshotDiffResponse\022!\n\031" +
      "snapshot_diff_result_json\030\001 \001(\t\"\366\001\n\030Trav" +
      "erseRelationsRequest\022\021\n\troot_path\030\001 \001(\t\022" +
      "\r\n\005paths\030\002 \003(\t\022\030\n\020parser_opts_json\030\003 \001(\t" +
      "\022\021\n\tdirection\030\004 \001(\t\022\023\n\013start_nodes\030\005 \003(\t" +
      "\022\026\n\016relation_types\030\006 \003(\t\022\025\n\rresolved_onl" +
      "y\030\007 \001(\t\022\024\n\014budgets_json\030\010 \001(\t\022\023\n\013snapsho" +
      "t_id\030\t \001(\t\022\034\n\024language_policy_json\030\n \001(\t" +
      "\"C\n\031TraverseRelationsResponse\022&\n\036travers" +
      "e_relations_result_json\030\001 \001(\t2\211\007\n\016Runtim" +
      "eService\022W\n\006Health\022%.semidx.runtime.grpc" +
      ".v1.HealthRequest\032&.semidx.runtime.grpc." +
      "v1.HealthResponse\022f\n\013CreateIndex\022*.semid" +
      "x.runtime.grpc.v1.CreateIndexRequest\032+.s" +
      "emidx.runtime.grpc.v1.CreateIndexRespons" +
      "e\022o\n\016ResolveContext\022-.semidx.runtime.grp" +
      "c.v1.ResolveContextRequest\032..semidx.runt" +
      "ime.grpc.v1.ResolveContextResponse\022l\n\rEx" +
      "pandContext\022,.semidx.runtime.grpc.v1.Exp" +
      "andContextRequest\032-.semidx.runtime.grpc." +
      "v1.ExpandContextResponse\022{\n\022FetchContext" +
      "Detail\0221.semidx.runtime.grpc.v1.FetchCon" +
      "textDetailRequest\0322.semidx.runtime.grpc." +
      "v1.FetchContextDetailResponse\022u\n\020Literal" +
      "FileSlice\022/.semidx.runtime.grpc.v1.Liter" +
      "alFileSliceRequest\0320.semidx.runtime.grpc" +
      ".v1.LiteralFileSliceResponse\022i\n\014Snapshot" +
      "Diff\022+.semidx.runtime.grpc.v1.SnapshotDi" +
      "ffRequest\032,.semidx.runtime.grpc.v1.Snaps" +
      "hotDiffResponse\022x\n\021TraverseRelations\0220.s" +
      "emidx.runtime.grpc.v1.TraverseRelationsR" +
      "equest\0321.semidx.runtime.grpc.v1.Traverse" +
      "RelationsResponseB(\n\026semidx.runtime.grpc" +
      ".v1B\014RuntimeProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_semidx_runtime_grpc_v1_HealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_semidx_runtime_grpc_v1_HealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_HealthRequest_descriptor,
        new java.lang.String[] { });
    internal_static_semidx_runtime_grpc_v1_HealthResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_semidx_runtime_grpc_v1_HealthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_HealthResponse_descriptor,
        new java.lang.String[] { "Status", "Service", "CapabilitiesJson", });
    internal_static_semidx_runtime_grpc_v1_CreateIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_semidx_runtime_grpc_v1_CreateIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_CreateIndexRequest_descriptor,
        new java.lang.String[] { "RootPath", "Paths", "ParserOptsJson", "LanguagePolicyJson", });
    internal_static_semidx_runtime_grpc_v1_CreateIndexResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_semidx_runtime_grpc_v1_CreateIndexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_CreateIndexResponse_descriptor,
        new java.lang.String[] { "SnapshotId", "IndexedAt", "FileCount", "UnitCount", "RepoMapJson", "IndexLifecycleJson", "ProviderSummaryJson", });
    internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_ResolveContextRequest_descriptor,
        new java.lang.String[] { "RootPath", "Paths", "ParserOptsJson", "QueryJson", "RetrievalPolicyJson", "LanguagePolicyJson", });
    internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_ResolveContextResponse_descriptor,
        new java.lang.String[] { "SelectionResultJson", });
    internal_static_semidx_runtime_grpc_v1_ExpandContextRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_semidx_runtime_grpc_v1_ExpandContextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_ExpandContextRequest_descriptor,
        new java.lang.String[] { "RootPath", "Paths", "ParserOptsJson", "SelectionId", "SnapshotId", "UnitIds", "IncludeImpactHints", "LanguagePolicyJson", });
    internal_static_semidx_runtime_grpc_v1_ExpandContextResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_semidx_runtime_grpc_v1_ExpandContextResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_ExpandContextResponse_descriptor,
        new java.lang.String[] { "ExpansionResultJson", });
    internal_static_semidx_runtime_grpc_v1_FetchContextDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_semidx_runtime_grpc_v1_FetchContextDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_FetchContextDetailRequest_descriptor,
        new java.lang.String[] { "RootPath", "Paths", "ParserOptsJson", "SelectionId", "SnapshotId", "UnitIds", "DetailLevel", "LanguagePolicyJson", });
    internal_static_semidx_runtime_grpc_v1_FetchContextDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_semidx_runtime_grpc_v1_FetchContextDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_FetchContextDetailResponse_descriptor,
        new java.lang.String[] { "DetailResultJson", });
    internal_static_semidx_runtime_grpc_v1_LiteralFileSliceRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_semidx_runtime_grpc_v1_LiteralFileSliceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_LiteralFileSliceRequest_descriptor,
        new java.lang.String[] { "RootPath", "Paths", "ParserOptsJson", "SelectionId", "SnapshotId", "Path", "StartLine", "EndLine", "LanguagePolicyJson", });
    internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_LiteralFileSliceResponse_descriptor,
        new java.lang.String[] { "LiteralSliceResultJson", });
    internal_static_semidx_runtime_grpc_v1_SnapshotDiffRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_semidx_runtime_grpc_v1_SnapshotDiffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_SnapshotDiffRequest_descriptor,
        new java.lang.String[] { "RootPath", "Paths", "ParserOptsJson", "BaselineSnapshotId", "IncludeUnchanged", "LanguagePolicyJson", });
    internal_static_semidx_runtime_grpc_v1_SnapshotDiffResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_semidx_runtime_grpc_v1_SnapshotDiffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_SnapshotDiffResponse_descriptor,
        new java.lang.String[] { "SnapshotDiffResultJson", });
    internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_descriptor,
        new java.lang.String[] { "RootPath", "Paths", "ParserOptsJson", "Direction", "StartNodes", "RelationTypes", "ResolvedOnly", "BudgetsJson", "SnapshotId", "LanguagePolicyJson", });
    internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_descriptor,
        new java.lang.String[] { "TraverseRelationsResultJson", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
