// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface SnapshotDiffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.SnapshotDiffResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string snapshot_diff_result_json = 1;</code>
   * @return The snapshotDiffResultJson.
   */
  java.lang.String getSnapshotDiffResultJson();
  /**
   * <code>string snapshot_diff_result_json = 1;</code>
   * @return The bytes for snapshotDiffResultJson.
   */
  com.google.protobuf.ByteString
      getSnapshotDiffResultJsonBytes();
}
