// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

/**
 * Protobuf type {@code semidx.runtime.grpc.v1.TraverseRelationsRequest}
 */
public final class TraverseRelationsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:semidx.runtime.grpc.v1.TraverseRelationsRequest)
    TraverseRelationsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TraverseRelationsRequest.newBuilder() to construct.
  private TraverseRelationsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TraverseRelationsRequest() {
    rootPath_ = "";
    paths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    parserOptsJson_ = "";
    direction_ = "";
    startNodes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    relationTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    resolvedOnly_ = "";
    budgetsJson_ = "";
    snapshotId_ = "";
    languagePolicyJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TraverseRelationsRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            semidx.runtime.grpc.v1.TraverseRelationsRequest.class, semidx.runtime.grpc.v1.TraverseRelationsRequest.Builder.class);
  }

  public static final int ROOT_PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rootPath_ = "";
  /**
   * <code>string root_path = 1;</code>
   * @return The rootPath.
   */
  @java.lang.Override
  public java.lang.String getRootPath() {
    java.lang.Object ref = rootPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rootPath_ = s;
      return s;
    }
  }
  /**
   * <code>string root_path = 1;</code>
   * @return The bytes for rootPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRootPathBytes() {
    java.lang.Object ref = rootPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rootPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATHS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList paths_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string paths = 2;</code>
   * @return A list containing the paths.
   */
  public com.google.protobuf.ProtocolStringList
      getPathsList() {
    return paths_;
  }
  /**
   * <code>repeated string paths = 2;</code>
   * @return The count of paths.
   */
  public int getPathsCount() {
    return paths_.size();
  }
  /**
   * <code>repeated string paths = 2;</code>
   * @param index The index of the element to return.
   * @return The paths at the given index.
   */
  public java.lang.String getPaths(int index) {
    return paths_.get(index);
  }
  /**
   * <code>repeated string paths = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the paths at the given index.
   */
  public com.google.protobuf.ByteString
      getPathsBytes(int index) {
    return paths_.getByteString(index);
  }

  public static final int PARSER_OPTS_JSON_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parserOptsJson_ = "";
  /**
   * <code>string parser_opts_json = 3;</code>
   * @return The parserOptsJson.
   */
  @java.lang.Override
  public java.lang.String getParserOptsJson() {
    java.lang.Object ref = parserOptsJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parserOptsJson_ = s;
      return s;
    }
  }
  /**
   * <code>string parser_opts_json = 3;</code>
   * @return The bytes for parserOptsJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParserOptsJsonBytes() {
    java.lang.Object ref = parserOptsJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parserOptsJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object direction_ = "";
  /**
   * <code>string direction = 4;</code>
   * @return The direction.
   */
  @java.lang.Override
  public java.lang.String getDirection() {
    java.lang.Object ref = direction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      direction_ = s;
      return s;
    }
  }
  /**
   * <code>string direction = 4;</code>
   * @return The bytes for direction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDirectionBytes() {
    java.lang.Object ref = direction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      direction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_NODES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList startNodes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string start_nodes = 5;</code>
   * @return A list containing the startNodes.
   */
  public com.google.protobuf.ProtocolStringList
      getStartNodesList() {
    return startNodes_;
  }
  /**
   * <code>repeated string start_nodes = 5;</code>
   * @return The count of startNodes.
   */
  public int getStartNodesCount() {
    return startNodes_.size();
  }
  /**
   * <code>repeated string start_nodes = 5;</code>
   * @param index The index of the element to return.
   * @return The startNodes at the given index.
   */
  public java.lang.String getStartNodes(int index) {
    return startNodes_.get(index);
  }
  /**
   * <code>repeated string start_nodes = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the startNodes at the given index.
   */
  public com.google.protobuf.ByteString
      getStartNodesBytes(int index) {
    return startNodes_.getByteString(index);
  }

  public static final int RELATION_TYPES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList relationTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string relation_types = 6;</code>
   * @return A list containing the relationTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getRelationTypesList() {
    return relationTypes_;
  }
  /**
   * <code>repeated string relation_types = 6;</code>
   * @return The count of relationTypes.
   */
  public int getRelationTypesCount() {
    return relationTypes_.size();
  }
  /**
   * <code>repeated string relation_types = 6;</code>
   * @param index The index of the element to return.
   * @return The relationTypes at the given index.
   */
  public java.lang.String getRelationTypes(int index) {
    return relationTypes_.get(index);
  }
  /**
   * <code>repeated string relation_types = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the relationTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getRelationTypesBytes(int index) {
    return relationTypes_.getByteString(index);
  }

  public static final int RESOLVED_ONLY_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resolvedOnly_ = "";
  /**
   * <code>string resolved_only = 7;</code>
   * @return The resolvedOnly.
   */
  @java.lang.Override
  public java.lang.String getResolvedOnly() {
    java.lang.Object ref = resolvedOnly_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resolvedOnly_ = s;
      return s;
    }
  }
  /**
   * <code>string resolved_only = 7;</code>
   * @return The bytes for resolvedOnly.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResolvedOnlyBytes() {
    java.lang.Object ref = resolvedOnly_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resolvedOnly_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUDGETS_JSON_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object budgetsJson_ = "";
  /**
   * <code>string budgets_json = 8;</code>
   * @return The budgetsJson.
   */
  @java.lang.Override
  public java.lang.String getBudgetsJson() {
    java.lang.Object ref = budgetsJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      budgetsJson_ = s;
      return s;
    }
  }
  /**
   * <code>string budgets_json = 8;</code>
   * @return The bytes for budgetsJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBudgetsJsonBytes() {
    java.lang.Object ref = budgetsJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      budgetsJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SNAPSHOT_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object snapshotId_ = "";
  /**
   * <code>string snapshot_id = 9;</code>
   * @return The snapshotId.
   */
  @java.lang.Override
  public java.lang.String getSnapshotId() {
    java.lang.Object ref = snapshotId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      snapshotId_ = s;
      return s;
    }
  }
  /**
   * <code>string snapshot_id = 9;</code>
   * @return The bytes for snapshotId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSnapshotIdBytes() {
    java.lang.Object ref = snapshotId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      snapshotId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGE_POLICY_JSON_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object languagePolicyJson_ = "";
  /**
   * <code>string language_policy_json = 10;</code>
   * @return The languagePolicyJson.
   */
  @java.lang.Override
  public java.lang.String getLanguagePolicyJson() {
    java.lang.Object ref = languagePolicyJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languagePolicyJson_ = s;
      return s;
    }
  }
  /**
   * <code>string language_policy_json = 10;</code>
   * @return The bytes for languagePolicyJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguagePolicyJsonBytes() {
    java.lang.Object ref = languagePolicyJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languagePolicyJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootPath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rootPath_);
    }
    for (int i = 0; i < paths_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, paths_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parserOptsJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parserOptsJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, direction_);
    }
    for (int i = 0; i < startNodes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, startNodes_.getRaw(i));
    }
    for (int i = 0; i < relationTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, relationTypes_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resolvedOnly_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, resolvedOnly_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(budgetsJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, budgetsJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(snapshotId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, snapshotId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languagePolicyJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, languagePolicyJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootPath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rootPath_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < paths_.size(); i++) {
        dataSize += computeStringSizeNoTag(paths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPathsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parserOptsJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, parserOptsJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, direction_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < startNodes_.size(); i++) {
        dataSize += computeStringSizeNoTag(startNodes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStartNodesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < relationTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(relationTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRelationTypesList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resolvedOnly_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, resolvedOnly_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(budgetsJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, budgetsJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(snapshotId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, snapshotId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languagePolicyJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, languagePolicyJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof semidx.runtime.grpc.v1.TraverseRelationsRequest)) {
      return super.equals(obj);
    }
    semidx.runtime.grpc.v1.TraverseRelationsRequest other = (semidx.runtime.grpc.v1.TraverseRelationsRequest) obj;

    if (!getRootPath()
        .equals(other.getRootPath())) return false;
    if (!getPathsList()
        .equals(other.getPathsList())) return false;
    if (!getParserOptsJson()
        .equals(other.getParserOptsJson())) return false;
    if (!getDirection()
        .equals(other.getDirection())) return false;
    if (!getStartNodesList()
        .equals(other.getStartNodesList())) return false;
    if (!getRelationTypesList()
        .equals(other.getRelationTypesList())) return false;
    if (!getResolvedOnly()
        .equals(other.getResolvedOnly())) return false;
    if (!getBudgetsJson()
        .equals(other.getBudgetsJson())) return false;
    if (!getSnapshotId()
        .equals(other.getSnapshotId())) return false;
    if (!getLanguagePolicyJson()
        .equals(other.getLanguagePolicyJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOT_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getRootPath().hashCode();
    if (getPathsCount() > 0) {
      hash = (37 * hash) + PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getPathsList().hashCode();
    }
    hash = (37 * hash) + PARSER_OPTS_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getParserOptsJson().hashCode();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getDirection().hashCode();
    if (getStartNodesCount() > 0) {
      hash = (37 * hash) + START_NODES_FIELD_NUMBER;
      hash = (53 * hash) + getStartNodesList().hashCode();
    }
    if (getRelationTypesCount() > 0) {
      hash = (37 * hash) + RELATION_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getRelationTypesList().hashCode();
    }
    hash = (37 * hash) + RESOLVED_ONLY_FIELD_NUMBER;
    hash = (53 * hash) + getResolvedOnly().hashCode();
    hash = (37 * hash) + BUDGETS_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getBudgetsJson().hashCode();
    hash = (37 * hash) + SNAPSHOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSnapshotId().hashCode();
    hash = (37 * hash) + LANGUAGE_POLICY_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getLanguagePolicyJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(semidx.runtime.grpc.v1.TraverseRelationsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code semidx.runtime.grpc.v1.TraverseRelationsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:semidx.runtime.grpc.v1.TraverseRelationsRequest)
      semidx.runtime.grpc.v1.TraverseRelationsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              semidx.runtime.grpc.v1.TraverseRelationsRequest.class, semidx.runtime.grpc.v1.TraverseRelationsRequest.Builder.class);
    }

    // Construct using semidx.runtime.grpc.v1.TraverseRelationsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rootPath_ = "";
      paths_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      parserOptsJson_ = "";
      direction_ = "";
      startNodes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      relationTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      resolvedOnly_ = "";
      budgetsJson_ = "";
      snapshotId_ = "";
      languagePolicyJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsRequest_descriptor;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.TraverseRelationsRequest getDefaultInstanceForType() {
      return semidx.runtime.grpc.v1.TraverseRelationsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.TraverseRelationsRequest build() {
      semidx.runtime.grpc.v1.TraverseRelationsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.TraverseRelationsRequest buildPartial() {
      semidx.runtime.grpc.v1.TraverseRelationsRequest result = new semidx.runtime.grpc.v1.TraverseRelationsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(semidx.runtime.grpc.v1.TraverseRelationsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rootPath_ = rootPath_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        paths_.makeImmutable();
        result.paths_ = paths_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.parserOptsJson_ = parserOptsJson_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.direction_ = direction_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        startNodes_.makeImmutable();
        result.startNodes_ = startNodes_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        relationTypes_.makeImmutable();
        result.relationTypes_ = relationTypes_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.resolvedOnly_ = resolvedOnly_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.budgetsJson_ = budgetsJson_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.snapshotId_ = snapshotId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.languagePolicyJson_ = languagePolicyJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof semidx.runtime.grpc.v1.TraverseRelationsRequest) {
        return mergeFrom((semidx.runtime.grpc.v1.TraverseRelationsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(semidx.runtime.grpc.v1.TraverseRelationsRequest other) {
      if (other == semidx.runtime.grpc.v1.TraverseRelationsRequest.getDefaultInstance()) return this;
      if (!other.getRootPath().isEmpty()) {
        rootPath_ = other.rootPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.paths_.isEmpty()) {
        if (paths_.isEmpty()) {
          paths_ = other.paths_;
          bitField0_ |= 0x00000002;
        } else {
          ensurePathsIsMutable();
          paths_.addAll(other.paths_);
        }
        onChanged();
      }
      if (!other.getParserOptsJson().isEmpty()) {
        parserOptsJson_ = other.parserOptsJson_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDirection().isEmpty()) {
        direction_ = other.direction_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.startNodes_.isEmpty()) {
        if (startNodes_.isEmpty()) {
          startNodes_ = other.startNodes_;
          bitField0_ |= 0x00000010;
        } else {
          ensureStartNodesIsMutable();
          startNodes_.addAll(other.startNodes_);
        }
        onChanged();
      }
      if (!other.relationTypes_.isEmpty()) {
        if (relationTypes_.isEmpty()) {
          relationTypes_ = other.relationTypes_;
          bitField0_ |= 0x00000020;
        } else {
          ensureRelationTypesIsMutable();
          relationTypes_.addAll(other.relationTypes_);
        }
        onChanged();
      }
      if (!other.getResolvedOnly().isEmpty()) {
        resolvedOnly_ = other.resolvedOnly_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getBudgetsJson().isEmpty()) {
        budgetsJson_ = other.budgetsJson_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getSnapshotId().isEmpty()) {
        snapshotId_ = other.snapshotId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getLanguagePolicyJson().isEmpty()) {
        languagePolicyJson_ = other.languagePolicyJson_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rootPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensurePathsIsMutable();
              paths_.add(s);
              break;
            } // case 18
            case 26: {
              parserOptsJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              direction_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureStartNodesIsMutable();
              startNodes_.add(s);
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRelationTypesIsMutable();
              relationTypes_.add(s);
              break;
            } // case 50
            case 58: {
              resolvedOnly_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              budgetsJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              snapshotId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              languagePolicyJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object rootPath_ = "";
    /**
     * <code>string root_path = 1;</code>
     * @return The rootPath.
     */
    public java.lang.String getRootPath() {
      java.lang.Object ref = rootPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rootPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string root_path = 1;</code>
     * @return The bytes for rootPath.
     */
    public com.google.protobuf.ByteString
        getRootPathBytes() {
      java.lang.Object ref = rootPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rootPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string root_path = 1;</code>
     * @param value The rootPath to set.
     * @return This builder for chaining.
     */
    public Builder setRootPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rootPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string root_path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRootPath() {
      rootPath_ = getDefaultInstance().getRootPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string root_path = 1;</code>
     * @param value The bytes for rootPath to set.
     * @return This builder for chaining.
     */
    public Builder setRootPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rootPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList paths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensurePathsIsMutable() {
      if (!paths_.isModifiable()) {
        paths_ = new com.google.protobuf.LazyStringArrayList(paths_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @return A list containing the paths.
     */
    public com.google.protobuf.ProtocolStringList
        getPathsList() {
      paths_.makeImmutable();
      return paths_;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @return The count of paths.
     */
    public int getPathsCount() {
      return paths_.size();
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param index The index of the element to return.
     * @return The paths at the given index.
     */
    public java.lang.String getPaths(int index) {
      return paths_.get(index);
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paths at the given index.
     */
    public com.google.protobuf.ByteString
        getPathsBytes(int index) {
      return paths_.getByteString(index);
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param index The index to set the value at.
     * @param value The paths to set.
     * @return This builder for chaining.
     */
    public Builder setPaths(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePathsIsMutable();
      paths_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param value The paths to add.
     * @return This builder for chaining.
     */
    public Builder addPaths(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePathsIsMutable();
      paths_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param values The paths to add.
     * @return This builder for chaining.
     */
    public Builder addAllPaths(
        java.lang.Iterable<java.lang.String> values) {
      ensurePathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, paths_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaths() {
      paths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paths = 2;</code>
     * @param value The bytes of the paths to add.
     * @return This builder for chaining.
     */
    public Builder addPathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensurePathsIsMutable();
      paths_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object parserOptsJson_ = "";
    /**
     * <code>string parser_opts_json = 3;</code>
     * @return The parserOptsJson.
     */
    public java.lang.String getParserOptsJson() {
      java.lang.Object ref = parserOptsJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parserOptsJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parser_opts_json = 3;</code>
     * @return The bytes for parserOptsJson.
     */
    public com.google.protobuf.ByteString
        getParserOptsJsonBytes() {
      java.lang.Object ref = parserOptsJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parserOptsJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parser_opts_json = 3;</code>
     * @param value The parserOptsJson to set.
     * @return This builder for chaining.
     */
    public Builder setParserOptsJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parserOptsJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string parser_opts_json = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParserOptsJson() {
      parserOptsJson_ = getDefaultInstance().getParserOptsJson();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string parser_opts_json = 3;</code>
     * @param value The bytes for parserOptsJson to set.
     * @return This builder for chaining.
     */
    public Builder setParserOptsJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parserOptsJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object direction_ = "";
    /**
     * <code>string direction = 4;</code>
     * @return The direction.
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string direction = 4;</code>
     * @return The bytes for direction.
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string direction = 4;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      direction_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string direction = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      direction_ = getDefaultInstance().getDirection();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string direction = 4;</code>
     * @param value The bytes for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      direction_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList startNodes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureStartNodesIsMutable() {
      if (!startNodes_.isModifiable()) {
        startNodes_ = new com.google.protobuf.LazyStringArrayList(startNodes_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @return A list containing the startNodes.
     */
    public com.google.protobuf.ProtocolStringList
        getStartNodesList() {
      startNodes_.makeImmutable();
      return startNodes_;
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @return The count of startNodes.
     */
    public int getStartNodesCount() {
      return startNodes_.size();
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @param index The index of the element to return.
     * @return The startNodes at the given index.
     */
    public java.lang.String getStartNodes(int index) {
      return startNodes_.get(index);
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the startNodes at the given index.
     */
    public com.google.protobuf.ByteString
        getStartNodesBytes(int index) {
      return startNodes_.getByteString(index);
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @param index The index to set the value at.
     * @param value The startNodes to set.
     * @return This builder for chaining.
     */
    public Builder setStartNodes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStartNodesIsMutable();
      startNodes_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @param value The startNodes to add.
     * @return This builder for chaining.
     */
    public Builder addStartNodes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStartNodesIsMutable();
      startNodes_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @param values The startNodes to add.
     * @return This builder for chaining.
     */
    public Builder addAllStartNodes(
        java.lang.Iterable<java.lang.String> values) {
      ensureStartNodesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, startNodes_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartNodes() {
      startNodes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string start_nodes = 5;</code>
     * @param value The bytes of the startNodes to add.
     * @return This builder for chaining.
     */
    public Builder addStartNodesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureStartNodesIsMutable();
      startNodes_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList relationTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureRelationTypesIsMutable() {
      if (!relationTypes_.isModifiable()) {
        relationTypes_ = new com.google.protobuf.LazyStringArrayList(relationTypes_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @return A list containing the relationTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getRelationTypesList() {
      relationTypes_.makeImmutable();
      return relationTypes_;
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @return The count of relationTypes.
     */
    public int getRelationTypesCount() {
      return relationTypes_.size();
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @param index The index of the element to return.
     * @return The relationTypes at the given index.
     */
    public java.lang.String getRelationTypes(int index) {
      return relationTypes_.get(index);
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the relationTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getRelationTypesBytes(int index) {
      return relationTypes_.getByteString(index);
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @param index The index to set the value at.
     * @param value The relationTypes to set.
     * @return This builder for chaining.
     */
    public Builder setRelationTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRelationTypesIsMutable();
      relationTypes_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @param value The relationTypes to add.
     * @return This builder for chaining.
     */
    public Builder addRelationTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRelationTypesIsMutable();
      relationTypes_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @param values The relationTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllRelationTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureRelationTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, relationTypes_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRelationTypes() {
      relationTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string relation_types = 6;</code>
     * @param value The bytes of the relationTypes to add.
     * @return This builder for chaining.
     */
    public Builder addRelationTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureRelationTypesIsMutable();
      relationTypes_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object resolvedOnly_ = "";
    /**
     * <code>string resolved_only = 7;</code>
     * @return The resolvedOnly.
     */
    public java.lang.String getResolvedOnly() {
      java.lang.Object ref = resolvedOnly_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resolvedOnly_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resolved_only = 7;</code>
     * @return The bytes for resolvedOnly.
     */
    public com.google.protobuf.ByteString
        getResolvedOnlyBytes() {
      java.lang.Object ref = resolvedOnly_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resolvedOnly_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resolved_only = 7;</code>
     * @param value The resolvedOnly to set.
     * @return This builder for chaining.
     */
    public Builder setResolvedOnly(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resolvedOnly_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string resolved_only = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResolvedOnly() {
      resolvedOnly_ = getDefaultInstance().getResolvedOnly();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string resolved_only = 7;</code>
     * @param value The bytes for resolvedOnly to set.
     * @return This builder for chaining.
     */
    public Builder setResolvedOnlyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resolvedOnly_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object budgetsJson_ = "";
    /**
     * <code>string budgets_json = 8;</code>
     * @return The budgetsJson.
     */
    public java.lang.String getBudgetsJson() {
      java.lang.Object ref = budgetsJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        budgetsJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string budgets_json = 8;</code>
     * @return The bytes for budgetsJson.
     */
    public com.google.protobuf.ByteString
        getBudgetsJsonBytes() {
      java.lang.Object ref = budgetsJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        budgetsJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string budgets_json = 8;</code>
     * @param value The budgetsJson to set.
     * @return This builder for chaining.
     */
    public Builder setBudgetsJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      budgetsJson_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string budgets_json = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBudgetsJson() {
      budgetsJson_ = getDefaultInstance().getBudgetsJson();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string budgets_json = 8;</code>
     * @param value The bytes for budgetsJson to set.
     * @return This builder for chaining.
     */
    public Builder setBudgetsJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      budgetsJson_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object snapshotId_ = "";
    /**
     * <code>string snapshot_id = 9;</code>
     * @return The snapshotId.
     */
    public java.lang.String getSnapshotId() {
      java.lang.Object ref = snapshotId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        snapshotId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string snapshot_id = 9;</code>
     * @return The bytes for snapshotId.
     */
    public com.google.protobuf.ByteString
        getSnapshotIdBytes() {
      java.lang.Object ref = snapshotId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        snapshotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string snapshot_id = 9;</code>
     * @param value The snapshotId to set.
     * @return This builder for chaining.
     */
    public Builder setSnapshotId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      snapshotId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string snapshot_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSnapshotId() {
      snapshotId_ = getDefaultInstance().getSnapshotId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string snapshot_id = 9;</code>
     * @param value The bytes for snapshotId to set.
     * @return This builder for chaining.
     */
    public Builder setSnapshotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      snapshotId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object languagePolicyJson_ = "";
    /**
     * <code>string language_policy_json = 10;</code>
     * @return The languagePolicyJson.
     */
    public java.lang.String getLanguagePolicyJson() {
      java.lang.Object ref = languagePolicyJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languagePolicyJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string language_policy_json = 10;</code>
     * @return The bytes for languagePolicyJson.
     */
    public com.google.protobuf.ByteString
        getLanguagePolicyJsonBytes() {
      java.lang.Object ref = languagePolicyJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languagePolicyJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string language_policy_json = 10;</code>
     * @param value The languagePolicyJson to set.
     * @return This builder for chaining.
     */
    public Builder setLanguagePolicyJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      languagePolicyJson_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string language_policy_json = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguagePolicyJson() {
      languagePolicyJson_ = getDefaultInstance().getLanguagePolicyJson();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string language_policy_json = 10;</code>
     * @param value The bytes for languagePolicyJson to set.
     * @return This builder for chaining.
     */
    public Builder setLanguagePolicyJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      languagePolicyJson_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:semidx.runtime.grpc.v1.TraverseRelationsRequest)
  }

  // @@protoc_insertion_point(class_scope:semidx.runtime.grpc.v1.TraverseRelationsRequest)
  private static final semidx.runtime.grpc.v1.TraverseRelationsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new semidx.runtime.grpc.v1.TraverseRelationsRequest();
  }

  public static semidx.runtime.grpc.v1.TraverseRelationsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TraverseRelationsRequest>
      PARSER = new com.google.protobuf.AbstractParser<TraverseRelationsRequest>() {
    @java.lang.Override
    public TraverseRelationsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TraverseRelationsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TraverseRelationsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public semidx.runtime.grpc.v1.TraverseRelationsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

