// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

public interface TraverseRelationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:semidx.runtime.grpc.v1.TraverseRelationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string traverse_relations_result_json = 1;</code>
   * @return The traverseRelationsResultJson.
   */
  java.lang.String getTraverseRelationsResultJson();
  /**
   * <code>string traverse_relations_result_json = 1;</code>
   * @return The bytes for traverseRelationsResultJson.
   */
  com.google.protobuf.ByteString
      getTraverseRelationsResultJsonBytes();
}
