// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semidx/runtime/grpc/v1/runtime.proto

// Protobuf Java Version: 3.25.1
package semidx.runtime.grpc.v1;

/**
 * Protobuf type {@code semidx.runtime.grpc.v1.TraverseRelationsResponse}
 */
public final class TraverseRelationsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:semidx.runtime.grpc.v1.TraverseRelationsResponse)
    TraverseRelationsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TraverseRelationsResponse.newBuilder() to construct.
  private TraverseRelationsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TraverseRelationsResponse() {
    traverseRelationsResultJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TraverseRelationsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            semidx.runtime.grpc.v1.TraverseRelationsResponse.class, semidx.runtime.grpc.v1.TraverseRelationsResponse.Builder.class);
  }

  public static final int TRAVERSE_RELATIONS_RESULT_JSON_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traverseRelationsResultJson_ = "";
  /**
   * <code>string traverse_relations_result_json = 1;</code>
   * @return The traverseRelationsResultJson.
   */
  @java.lang.Override
  public java.lang.String getTraverseRelationsResultJson() {
    java.lang.Object ref = traverseRelationsResultJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traverseRelationsResultJson_ = s;
      return s;
    }
  }
  /**
   * <code>string traverse_relations_result_json = 1;</code>
   * @return The bytes for traverseRelationsResultJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraverseRelationsResultJsonBytes() {
    java.lang.Object ref = traverseRelationsResultJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traverseRelationsResultJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traverseRelationsResultJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traverseRelationsResultJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traverseRelationsResultJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traverseRelationsResultJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof semidx.runtime.grpc.v1.TraverseRelationsResponse)) {
      return super.equals(obj);
    }
    semidx.runtime.grpc.v1.TraverseRelationsResponse other = (semidx.runtime.grpc.v1.TraverseRelationsResponse) obj;

    if (!getTraverseRelationsResultJson()
        .equals(other.getTraverseRelationsResultJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRAVERSE_RELATIONS_RESULT_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getTraverseRelationsResultJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static semidx.runtime.grpc.v1.TraverseRelationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(semidx.runtime.grpc.v1.TraverseRelationsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code semidx.runtime.grpc.v1.TraverseRelationsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:semidx.runtime.grpc.v1.TraverseRelationsResponse)
      semidx.runtime.grpc.v1.TraverseRelationsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              semidx.runtime.grpc.v1.TraverseRelationsResponse.class, semidx.runtime.grpc.v1.TraverseRelationsResponse.Builder.class);
    }

    // Construct using semidx.runtime.grpc.v1.TraverseRelationsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      traverseRelationsResultJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return semidx.runtime.grpc.v1.RuntimeProto.internal_static_semidx_runtime_grpc_v1_TraverseRelationsResponse_descriptor;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.TraverseRelationsResponse getDefaultInstanceForType() {
      return semidx.runtime.grpc.v1.TraverseRelationsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.TraverseRelationsResponse build() {
      semidx.runtime.grpc.v1.TraverseRelationsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public semidx.runtime.grpc.v1.TraverseRelationsResponse buildPartial() {
      semidx.runtime.grpc.v1.TraverseRelationsResponse result = new semidx.runtime.grpc.v1.TraverseRelationsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(semidx.runtime.grpc.v1.TraverseRelationsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.traverseRelationsResultJson_ = traverseRelationsResultJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof semidx.runtime.grpc.v1.TraverseRelationsResponse) {
        return mergeFrom((semidx.runtime.grpc.v1.TraverseRelationsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(semidx.runtime.grpc.v1.TraverseRelationsResponse other) {
      if (other == semidx.runtime.grpc.v1.TraverseRelationsResponse.getDefaultInstance()) return this;
      if (!other.getTraverseRelationsResultJson().isEmpty()) {
        traverseRelationsResultJson_ = other.traverseRelationsResultJson_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              traverseRelationsResultJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object traverseRelationsResultJson_ = "";
    /**
     * <code>string traverse_relations_result_json = 1;</code>
     * @return The traverseRelationsResultJson.
     */
    public java.lang.String getTraverseRelationsResultJson() {
      java.lang.Object ref = traverseRelationsResultJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traverseRelationsResultJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string traverse_relations_result_json = 1;</code>
     * @return The bytes for traverseRelationsResultJson.
     */
    public com.google.protobuf.ByteString
        getTraverseRelationsResultJsonBytes() {
      java.lang.Object ref = traverseRelationsResultJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traverseRelationsResultJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string traverse_relations_result_json = 1;</code>
     * @param value The traverseRelationsResultJson to set.
     * @return This builder for chaining.
     */
    public Builder setTraverseRelationsResultJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traverseRelationsResultJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string traverse_relations_result_json = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraverseRelationsResultJson() {
      traverseRelationsResultJson_ = getDefaultInstance().getTraverseRelationsResultJson();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string traverse_relations_result_json = 1;</code>
     * @param value The bytes for traverseRelationsResultJson to set.
     * @return This builder for chaining.
     */
    public Builder setTraverseRelationsResultJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traverseRelationsResultJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:semidx.runtime.grpc.v1.TraverseRelationsResponse)
  }

  // @@protoc_insertion_point(class_scope:semidx.runtime.grpc.v1.TraverseRelationsResponse)
  private static final semidx.runtime.grpc.v1.TraverseRelationsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new semidx.runtime.grpc.v1.TraverseRelationsResponse();
  }

  public static semidx.runtime.grpc.v1.TraverseRelationsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TraverseRelationsResponse>
      PARSER = new com.google.protobuf.AbstractParser<TraverseRelationsResponse>() {
    @java.lang.Override
    public TraverseRelationsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TraverseRelationsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TraverseRelationsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public semidx.runtime.grpc.v1.TraverseRelationsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

