(ns semidx.runtime.providers.scip-typescript
  "Stage 3 of the Semantic Provider Authority Migration (plans/018, ADR-046):
  the TypeScript SCIP provider adapter. Shadow / default-off.

  SCIP is a project-level batch index, not a per-file parse. Unlike the Stage 2
  tree-sitter and regex adapters in `semidx.runtime.providers`, which run per file
  behind the ProviderPlan orchestrator, this adapter is a standalone entry point:
  `shadow-facts-for-project` runs the repo-managed `scip-typescript` CLI once over
  a project, reads the `.scip` with `semidx.runtime.scip`, normalizes it with
  `semidx.runtime.providers.scip-normalize`, applies a per-document stale gate,
  and returns arbitrated shadow facts. Reconciling a project-scoped provider with
  the per-file planning model is a later slice; it is deliberately not wired into
  `provider-selection` / `provider-execution` here, mirroring the standalone-seam
  choice Stage 2 made for the same reason. Nothing here touches default
  extraction.

  Source mode (owner-confirmed):

  - production: the `.scip` is generated by the repo-managed CLI, resolved
    through the ADR-047 chain used for tree-sitter — explicit option ->
    `SEMIDX_SCIP_TYPESCRIPT_CLI_PATH` -> repo-managed `.scip-toolchain/` ->
    ambient `PATH`;
  - a missing CLI is not an index-run error: `shadow-facts-for-project` returns
    an `:unavailable` result with diagnostics and no facts, and a caller
    degrades to tree-sitter / regex;
  - `facts-from-index` accepts an already-read SCIP index and is the test /
    fixture seam only, not a production source mode.

  Exact authority (ADR-046) requires the evidence to be anchored to the content
  it describes. Each SCIP document's `relative_path` is resolved against the
  project root and digested; a document whose workspace file is missing, or whose
  digest does not match a caller-supplied expected digest, contributes no facts
  and is reported as stale. The gate is document-level for this first slice:
  range-level invalidation is a later refinement (reports/024 finding F2)."
  (:require [clojure.java.io :as io]
            [clojure.java.shell :as sh]
            [clojure.string :as str]
            [semidx.runtime.fact-arbitration :as fact-arbitration]
            [semidx.runtime.providers.scip-normalize :as scip-normalize]
            [semidx.runtime.scip :as scip]
            [semidx.runtime.workspace-state :as workspace-state]))

(def provider-id "scip-typescript")
(def provider-version "1")

(def descriptor
  "Catalog descriptor for the SCIP TypeScript provider.

  Kept here rather than in `semidx.runtime.providers/descriptors` while the
  provider is project-scoped and standalone: adding it to the per-file catalog
  would route a per-file `run-provider` call at an engine that catalog cannot
  execute. Exposed so the later catalog-integration slice has one source of
  truth for the claim."
  {:provider_id provider-id
   :provider_version provider-version
   :languages ["typescript"]
   :classification "semantic"
   :engine :scip
   :scope :project
   :selectors {:extensions [".ts" ".tsx"]}
   :operation_capabilities {:definitions "exact"
                            :references "exact"}})

;; ---------------------------------------------------------------------------
;; CLI resolution (ADR-047-style chain)
;; ---------------------------------------------------------------------------

(defn- present-path
  "Trim a candidate to a non-blank string, or nil."
  [value]
  (let [s (some-> value str str/trim)]
    (when-not (str/blank? s) s)))

(defn- executable-file? [path]
  (let [f (io/file path)]
    (and (.isFile f) (.canExecute f))))

(defn- managed-cli-path
  "The repo-managed CLI installed by `scripts/setup-scip-typescript.sh`. The
  toolchain directory is resolved the same way that script resolves it:
  `:scip_toolchain_dir` option -> `SEMIDX_SCIP_TOOLCHAIN_DIR` -> `./.scip-toolchain`."
  [opts]
  (let [dir (or (present-path (:scip_toolchain_dir opts))
                (present-path (:scip-toolchain-dir opts))
                (present-path (System/getenv "SEMIDX_SCIP_TOOLCHAIN_DIR"))
                (str (io/file ".scip-toolchain")))
        managed (some-> dir io/file (io/file "node_modules/.bin/scip-typescript") .getPath)]
    (when (and managed (executable-file? managed))
      managed)))

(defn resolve-cli
  "Resolve the `scip-typescript` CLI path, or nil when none is available.

  Resolution order mirrors ADR-047: explicit option, environment, the
  repo-managed install, then ambient `PATH`. Only the first three are checked
  for an executable file here; a bare `\"scip-typescript\"` from `PATH` is
  returned unverified as a developer-convenience fallback and its absence surfaces
  when the index run fails."
  ([] (resolve-cli {}))
  ([opts]
   (or (let [p (present-path (:scip_typescript_cli_path opts))]
         (when (and p (executable-file? p)) p))
       (let [p (present-path (:scip-typescript-cli-path opts))]
         (when (and p (executable-file? p)) p))
       (let [p (present-path (System/getenv "SEMIDX_SCIP_TYPESCRIPT_CLI_PATH"))]
         (when (and p (executable-file? p)) p))
       (managed-cli-path opts)
       nil)))

(defn cli-version
  "Best-effort `scip-typescript --version`, or nil."
  [cli]
  (try
    (let [{:keys [exit out]} (sh/sh cli "--version")]
      (when (zero? (int exit))
        (present-path out)))
    (catch Exception _ nil)))

(defn provider-status
  "Observe whether the SCIP TypeScript provider can run right now.

  `ready` when the CLI resolves to an executable; otherwise `unavailable` with a
  `scip_cli_missing` reason code. This never runs the indexer."
  ([] (provider-status {}))
  ([opts]
   (let [cli (resolve-cli opts)
         base {:provider_id provider-id
               :observed_at (str (java.time.Instant/now))}]
     (if cli
       (assoc base :state "ready" :reason_codes [] :cli_path cli)
       (assoc base :state "unavailable" :reason_codes ["scip_cli_missing"])))))

;; ---------------------------------------------------------------------------
;; Index run
;; ---------------------------------------------------------------------------

(defn- run-scip-index!
  "Run `scip-typescript index` over `project-root` and return the parsed index
  data, or `{:error ...}` on a non-zero exit or an exception. The `.scip` is
  written to a temp file that is always removed."
  [cli project-root]
  (let [tmp (java.io.File/createTempFile "semidx-scip" ".scip")
        ;; `sh` resolves a relative program against `:dir`, not the JVM CWD, so
        ;; the repo-managed `.scip-toolchain/...` path must be absolute here.
        cli-file (io/file cli)
        cli* (if (.isFile cli-file) (.getAbsolutePath cli-file) cli)
        dir* (.getAbsolutePath (io/file (str project-root)))]
    (try
      (let [{:keys [exit err]} (sh/sh cli* "index" "--no-progress-bar"
                                      "--output" (.getPath tmp)
                                      :dir dir*)]
        (if (zero? (int exit))
          {:index (scip/read-index tmp)}
          {:error {:code :scip_index_failed
                   :exit (int exit)
                   :message (str "scip-typescript index exited " exit
                                 (when-let [e (present-path err)] (str ": " e)))}}))
      (catch Exception e
        {:error {:code :scip_index_failed
                 :message (str "scip-typescript index failed: " (.getMessage e))}})
      (finally
        (.delete tmp)))))

;; ---------------------------------------------------------------------------
;; Per-document stale gate
;; ---------------------------------------------------------------------------

(defn- workspace-digest
  "sha256 of the workspace file for `relative-path` under `project-root`, or nil
  when the file does not exist. Same basis as
  `semidx.runtime.workspace-state/sha256-file`, so a digest here is comparable to
  workspace freshness."
  [project-root relative-path]
  (let [f (io/file (str project-root) (str relative-path))]
    (when (.isFile f)
      (str "sha256:" (workspace-state/sha256-file f)))))

(defn- document-freshness
  "Classify one SCIP document against the workspace. Returns
  `{:state :fresh :content_digest ...}`, `{:state :missing}`, or
  `{:state :mismatch :expected ... :actual ...}`.

  `expected-digests` is an optional map of `relative-path` -> expected
  `sha256:...` digest (for example captured from a workspace-state snapshot taken
  before indexing); when it carries no entry for a document, a present file is
  fresh and its own digest is the anchor."
  [project-root relative-path expected-digests]
  (let [actual (workspace-digest project-root relative-path)
        expected (get expected-digests relative-path)]
    (cond
      (nil? actual) {:state :missing}
      (and expected (not= expected actual)) {:state :mismatch
                                             :expected expected
                                             :actual actual}
      :else {:state :fresh :content_digest actual})))

(defn- stale-diagnostic [relative-path freshness]
  (case (:state freshness)
    :missing {:code :scip_document_source_missing
              :document relative-path
              :message (str "SCIP covered " relative-path
                            " but its workspace file is missing; dropped from exact facts")}
    :mismatch {:code :scip_document_stale
               :document relative-path
               :expected (:expected freshness)
               :actual (:actual freshness)
               :message (str "SCIP artifact for " relative-path
                             " does not match the workspace file; dropped from exact facts")}))

;; ---------------------------------------------------------------------------
;; Fact emission
;; ---------------------------------------------------------------------------

(defn- facts->batches
  "Group normalized facts into one `FactBatch` per operation. Each fact from
  `scip-normalize` carries exactly one evidence record with one operation."
  [facts covered-paths complete?]
  (->> facts
       (group-by #(-> % :evidence first :operation))
       (sort-by key)
       (mapv (fn [[operation op-facts]]
               {:provider_id provider-id
                :provider_version provider-version
                :operation operation
                :freshness "exact"
                :source_identity {}
                :coverage {:paths (vec covered-paths)
                           :fact_kinds ["unit"]
                           :complete complete?}
                :diagnostics []
                :facts (vec op-facts)}))))

(defn- unmapped-summary [unmapped]
  (when (seq unmapped)
    {:code :scip_symbols_unmapped
     :count (count unmapped)
     :by_reason (into (sorted-map) (frequencies (map :reason unmapped)))
     :message (str (count unmapped)
                   " SCIP symbol occurrences were deliberately not turned into facts")}))

(defn facts-from-index
  "Turn an already-read SCIP index into arbitrated shadow facts.

  Test / fixture seam only — production callers use `shadow-facts-for-project`,
  which generates the index with the repo-managed CLI first.

  `opts`:
  - `:project-root` (required) — used to digest the workspace files SCIP covered;
  - `:expected-document-digests` — optional `relative-path` -> `sha256:...` map
    for the stale gate;
  - `:provider-id` / `:provider-version` — evidence provenance overrides."
  [scip-index {:keys [project-root expected-document-digests]
               prov-id :provider-id
               prov-version :provider-version
               :or {prov-id provider-id prov-version provider-version}}]
  (when-not project-root
    (throw (ex-info "facts-from-index requires :project-root to anchor exact facts"
                    {:error_code :missing_project_root})))
  (let [provider-id prov-id
        provider-version prov-version
        documents (:documents scip-index)
        graded (mapv (fn [doc]
                       (assoc doc :freshness
                              (document-freshness project-root (:relative-path doc)
                                                  expected-document-digests)))
                     documents)
        fresh (filterv #(= :fresh (:state (:freshness %))) graded)
        stale (filterv #(not= :fresh (:state (:freshness %))) graded)
        digest-by-path (into {} (map (juxt :relative-path
                                           (comp :content_digest :freshness))
                                     fresh))
        normalized (scip-normalize/normalize-index
                    {:documents fresh}
                    {:language "typescript"
                     :provider-id provider-id
                     :provider-version provider-version
                     :source-identity (fn [relative-path]
                                        {:content_digest (get digest-by-path relative-path)})})
        covered-paths (mapv :relative-path fresh)
        complete? (empty? stale)
        batches (facts->batches (:facts normalized) covered-paths complete?)
        arbitrated (fact-arbitration/arbitrate-batches batches)
        diagnostics (vec (concat (map #(stale-diagnostic (:relative-path %) (:freshness %))
                                      stale)
                                 (when-let [s (unmapped-summary (:unmapped normalized))]
                                   [s])))]
    {:provider_id provider-id
     :provider_version provider-version
     :result "ready"
     :facts (:facts arbitrated)
     ;; Pre-arbitration facts, one evidence record each, kept so a shadow
     ;; comparison can co-arbitrate the SCIP and legacy fact sets in one pass.
     :raw_facts (vec (:facts normalized))
     :batches (:batches arbitrated)
     :errors (:errors arbitrated)
     :diagnostics diagnostics
     :coverage {:covered_paths covered-paths
                :stale_documents (mapv :relative-path stale)
                :complete complete?}
     :unmapped (:unmapped normalized)}))

(defn shadow-facts-for-project
  "Run the repo-managed `scip-typescript` CLI over `root_path`, then normalize,
  gate, and arbitrate its output into shadow facts.

  Returns a map with `:result` one of:
  - `\"ready\"`   — the CLI ran and produced facts (see `facts-from-index`);
  - `\"unavailable\"` — no CLI resolved; `:reason_codes [\"scip_cli_missing\"]`,
    no facts, and the caller should degrade to tree-sitter / regex;
  - `\"failed\"`  — the CLI resolved but the index run errored; `:diagnostics`
    carries the reason and there are no facts.

  This never throws for a missing or failing toolchain and never writes to a
  snapshot."
  [{:keys [root_path expected_document_digests] :as opts}]
  (when-not root_path
    (throw (ex-info "shadow-facts-for-project requires :root_path"
                    {:error_code :missing_root_path})))
  (let [cli (resolve-cli opts)]
    (if-not cli
      {:provider_id provider-id
       :provider_version provider-version
       :result "unavailable"
       :reason_codes ["scip_cli_missing"]
       :facts []
       :batches []
       :errors []
       :diagnostics [{:code :scip_provider_unavailable
                      :message (str "no scip-typescript CLI resolved for " root_path
                                    "; degrade to tree-sitter/regex")}]
       :coverage {:covered_paths [] :stale_documents [] :complete false}
       :unmapped []}
      (let [{:keys [index error]} (run-scip-index! cli root_path)]
        (if error
          {:provider_id provider-id
           :provider_version provider-version
           :result "failed"
           :cli {:path cli :version (cli-version cli)}
           :facts []
           :batches []
           :errors []
           :diagnostics [error]
           :coverage {:covered_paths [] :stale_documents [] :complete false}
           :unmapped []}
          (-> (facts-from-index index {:project-root root_path
                                       :expected-document-digests expected_document_digests})
              (assoc :cli {:path cli :version (cli-version cli)})))))))
