(ns semidx.runtime.providers.scip-typescript
  "Stage 3 of the Semantic Provider Authority Migration (plans/018, ADR-046):
  the TypeScript SCIP provider adapter. On the default path since Stage 6,
  whenever its toolchain resolves.

  Everything language-neutral — the per-document stale gate, `FactBatch`
  assembly, and the result shapes — lives in
  `semidx.runtime.providers.scip-adapter`. What remains here is only how the
  scip-typescript toolchain is resolved and invoked.

  SCIP is a project-level batch index, not a per-file parse, so this adapter is
  not a `semidx.runtime.providers/run-provider` engine. Stage 4.5 gave that
  shape a home: `semidx.runtime.provider-batch` owns the status and run roles,
  runs `facts-for-project` once per project, and hands the resulting
  facts to per-file planning as batch coverage. Nothing here touches default
  extraction, and the provider stays default-off.

  Source mode (owner-confirmed):

  - production: the `.scip` is generated by the repo-managed CLI, resolved
    through the ADR-047 chain — explicit option ->
    `SEMIDX_SCIP_TYPESCRIPT_CLI_PATH` -> repo-managed `.scip-toolchain/` ->
    ambient `PATH`;
  - a missing CLI is not an index-run error: `facts-for-project` returns
    an `:unavailable` result with diagnostics and no facts, and a caller
    degrades to tree-sitter / regex;
  - `facts-from-index` accepts an already-read SCIP index and is the test /
    fixture seam only, not a production source mode."
  (:require [clojure.java.io :as io]
            [clojure.java.shell :as sh]
            [semidx.runtime.providers :as providers]
            [semidx.runtime.providers.scip-adapter :as scip-adapter]
            [semidx.runtime.scip :as scip]))

(def provider-id "scip-typescript")
(def provider-version "1")
(def language "typescript")

(def descriptor
  "Catalog descriptor for the SCIP TypeScript provider.

  Stage 4.5 moved the data into `semidx.runtime.providers/project-descriptors`,
  which is now the single source of truth for every provider claim; this var
  re-exports it so existing callers keep one name. The dependency runs adapter
  -> catalog and never the other way, because the catalog is on the per-file
  planning path and must not load this namespace's protobuf classes."
  (providers/descriptor provider-id))

;; ---------------------------------------------------------------------------
;; CLI resolution (ADR-047-style chain)
;; ---------------------------------------------------------------------------

(defn- managed-cli-path
  "The repo-managed CLI installed by `scripts/setup-scip-typescript.sh`. The
  toolchain directory is resolved the same way that script resolves it:
  `:scip_toolchain_dir` option -> `SEMIDX_SCIP_TOOLCHAIN_DIR` -> `./.scip-toolchain`."
  [opts]
  (let [dir (or (scip-adapter/present-path (:scip_toolchain_dir opts))
                (scip-adapter/present-path (:scip-toolchain-dir opts))
                (scip-adapter/present-path (System/getenv "SEMIDX_SCIP_TOOLCHAIN_DIR"))
                (str (io/file ".scip-toolchain")))
        managed (some-> dir io/file (io/file "node_modules/.bin/scip-typescript") .getPath)]
    (when (and managed (scip-adapter/executable-file? managed))
      managed)))

(defn resolve-cli
  "Resolve the `scip-typescript` CLI path, or nil when none is available.

  Resolution order mirrors ADR-047: explicit option, environment, the
  repo-managed install, then ambient `PATH`. Only the first three are checked
  for an executable file here; a bare `\"scip-typescript\"` from `PATH` is
  returned unverified as a developer-convenience fallback and its absence surfaces
  when the index run fails."
  ([] (resolve-cli {}))
  ([opts]
   (or (let [p (scip-adapter/present-path (:scip_typescript_cli_path opts))]
         (when (and p (scip-adapter/executable-file? p)) p))
       (let [p (scip-adapter/present-path (:scip-typescript-cli-path opts))]
         (when (and p (scip-adapter/executable-file? p)) p))
       (let [p (scip-adapter/present-path (System/getenv "SEMIDX_SCIP_TYPESCRIPT_CLI_PATH"))]
         (when (and p (scip-adapter/executable-file? p)) p))
       (managed-cli-path opts)
       nil)))

(defn cli-version
  "Best-effort `scip-typescript --version`, or nil."
  [cli]
  (try
    (let [{:keys [exit out]} (sh/sh cli "--version")]
      (when (zero? (int exit))
        (scip-adapter/present-path out)))
    ;; Best-effort by contract: a version we cannot read is reported as nil in
    ;; the result, not printed. Anything on stdout would corrupt the MCP stdio
    ;; transport these adapters run behind.
    (catch Exception _ nil)))

(defn provider-status
  "Observe whether the SCIP TypeScript provider can run right now.

  `ready` when the CLI resolves to an executable; otherwise `unavailable` with a
  `scip_cli_missing` reason code. This never runs the indexer."
  ([] (provider-status {}))
  ([opts]
   (let [cli (resolve-cli opts)
         base {:provider_id provider-id
               :observed_at (str (java.time.Instant/now))}]
     (if cli
       (assoc base :state "ready" :reason_codes [] :cli_path cli)
       (assoc base :state "unavailable" :reason_codes ["scip_cli_missing"])))))

;; ---------------------------------------------------------------------------
;; Index run
;; ---------------------------------------------------------------------------

(defn- run-scip-index!
  "Run `scip-typescript index` over `project-root` and return the parsed index
  data, or `{:error ...}` on a non-zero exit or an exception. The `.scip` is
  written to a temp file that is always removed."
  [cli project-root]
  (let [tmp (java.io.File/createTempFile "semidx-scip" ".scip")
        ;; `sh` resolves a relative program against `:dir`, not the JVM CWD, so
        ;; the repo-managed `.scip-toolchain/...` path must be absolute here.
        cli-file (io/file cli)
        cli* (if (.isFile cli-file) (.getAbsolutePath cli-file) cli)
        dir* (.getAbsolutePath (io/file (str project-root)))]
    (try
      (let [{:keys [exit err]} (sh/sh cli* "index" "--no-progress-bar"
                                      "--output" (.getPath tmp)
                                      :dir dir*)]
        (if (zero? (int exit))
          {:index (scip/read-index tmp)}
          {:error {:code :scip_index_failed
                   :exit (int exit)
                   :message (str "scip-typescript index exited " exit
                                 (when-let [e (scip-adapter/present-path err)]
                                   (str ": " e)))}}))
      (catch Exception e
        {:error {:code :scip_index_failed
                 :message (str "scip-typescript index failed: " (.getMessage e))}})
      (finally
        (.delete tmp)))))

;; ---------------------------------------------------------------------------
;; Entry points
;; ---------------------------------------------------------------------------

(defn facts-from-index
  "Turn an already-read SCIP index into arbitrated shadow facts.

  Test / fixture seam only — production callers use `facts-for-project`,
  which generates the index with the repo-managed CLI first.

  `opts`:
  - `:project-root` (required) — used to digest the workspace files SCIP covered;
  - `:expected-document-digests` — optional `relative-path` -> `sha256:...` map
    for the stale gate;
  - `:provider-id` / `:provider-version` — evidence provenance overrides."
  [scip-index opts]
  (scip-adapter/facts-from-index
   scip-index
   (merge {:language language
           :provider-id provider-id
           :provider-version provider-version}
          (select-keys opts [:project-root :expected-document-digests
                             :provider-id :provider-version]))))

(defn facts-for-project
  "Run the repo-managed `scip-typescript` CLI over `root_path`, then normalize,
  gate, and arbitrate its output into shadow facts.

  Returns a map with `:result` one of:
  - `\"ready\"`   — the CLI ran and produced facts (see `facts-from-index`);
  - `\"unavailable\"` — no CLI resolved; `:reason_codes [\"scip_cli_missing\"]`,
    no facts, and the caller should degrade to tree-sitter / regex;
  - `\"failed\"`  — the CLI resolved but the index run errored; `:diagnostics`
    carries the reason and there are no facts.

  This never throws for a missing or failing toolchain and never writes to a
  snapshot."
  [{:keys [root_path expected_document_digests] :as opts}]
  (when-not root_path
    (throw (ex-info "facts-for-project requires :root_path"
                    {:error_code :missing_root_path})))
  (let [cli (resolve-cli opts)]
    (if-not cli
      (scip-adapter/unavailable-result
       {:provider-id provider-id
        :provider-version provider-version
        :reason-codes ["scip_cli_missing"]
        :message (str "no scip-typescript CLI resolved for " root_path
                      "; degrade to tree-sitter/regex")})
      (let [{:keys [index error]} (run-scip-index! cli root_path)]
        (if error
          (assoc (scip-adapter/failed-result {:provider-id provider-id
                                              :provider-version provider-version
                                              :diagnostic error})
                 :cli {:path cli :version (cli-version cli)})
          (-> (facts-from-index index
                                {:project-root root_path
                                 :expected-document-digests expected_document_digests})
              (assoc :cli {:path cli :version (cli-version cli)})))))))
