#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

usage() {
  cat <<'EOF'
Usage:
  ./scripts/new-language-adapter.sh <language> [--ext .ext1,.ext2] [--dry-run]

Examples:
  ./scripts/new-language-adapter.sh ruby --ext .rb
  ./scripts/new-language-adapter.sh typescript --ext .ts,.tsx
  ./scripts/new-language-adapter.sh go --ext .go --dry-run
EOF
}

if [[ $# -ge 1 && ( "$1" == "-h" || "$1" == "--help" ) ]]; then
  usage
  exit 0
fi

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

LANG_INPUT="$1"
shift

DRY_RUN="false"
EXT_CSV=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ext)
      EXT_CSV="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

LANG_ID="$(echo "$LANG_INPUT" | tr '[:upper:]-' '[:lower:]_' | sed 's/[^a-z0-9_]/_/g' | sed 's/__*/_/g' | sed 's/^_//;s/_$//')"
if [[ -z "$LANG_ID" ]]; then
  echo "invalid language value: $LANG_INPUT" >&2
  exit 1
fi

LANG_NS="$(echo "$LANG_ID" | tr '_' '-')"
LANG_TITLE="$(echo "$LANG_NS" | awk -F'-' '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2)}; print $0}')"

if [[ -z "$EXT_CSV" ]]; then
  EXT_CSV=".$LANG_ID"
fi

IFS=',' read -r -a RAW_EXTS <<< "$EXT_CSV"
EXTS=()
for ext in "${RAW_EXTS[@]}"; do
  trimmed="$(echo "$ext" | xargs)"
  if [[ -z "$trimmed" ]]; then
    continue
  fi
  if [[ "$trimmed" != .* ]]; then
    trimmed=".$trimmed"
  fi
  EXTS+=("$trimmed")
done

if [[ "${#EXTS[@]}" -eq 0 ]]; then
  echo "no valid extensions provided" >&2
  exit 1
fi

PRIMARY_EXT="${EXTS[0]}"
PRIMARY_EXT_NO_DOT="${PRIMARY_EXT#.}"

log() {
  printf '%s\n' "$*"
}

write_file() {
  local path="$1"
  local content="$2"
  if [[ -f "$path" ]]; then
    log "skip existing: $path"
    return 0
  fi
  if [[ "$DRY_RUN" == "true" ]]; then
    log "[dry-run] create: $path"
    return 0
  fi
  mkdir -p "$(dirname "$path")"
  printf '%s' "$content" > "$path"
  log "created: $path"
}

update_file_with_awk() {
  local path="$1"
  shift
  if [[ "$DRY_RUN" == "true" ]]; then
    log "[dry-run] patch: $path"
    return 0
  fi
  local tmp
  tmp="$(mktemp)"
  awk "$@" "$path" > "$tmp"
  mv "$tmp" "$path"
  log "patched: $path"
}

build_ext_cond_expr() {
  if [[ "${#EXTS[@]}" -eq 1 ]]; then
    printf '(str/ends-with? path "%s")' "${EXTS[0]}"
    return 0
  fi
  local expr="(or"
  local ext
  for ext in "${EXTS[@]}"; do
    expr="$expr (str/ends-with? path \"$ext\")"
  done
  expr="$expr)"
  printf '%s' "$expr"
}

ADAPTERS_FILE="src/semidx/runtime/adapters.clj"
TEST_RUNNER_FILE="src/semidx/test_runner.clj"
CORPUS_FILE="fixtures/retrieval/corpus.json"
FIXTURE_HAPPY="fixtures/retrieval/${LANG_ID}-happy-path.json"
FIXTURE_AMBIG="fixtures/retrieval/${LANG_ID}-ambiguity.json"
DOC_ONBOARDING="docs/language-onboarding/${LANG_ID}.md"
TEST_FILE="test/semidx/${LANG_ID}_onboarding_test.clj"

EXT_EXPR="$(build_ext_cond_expr)"

if ! grep -q "\"${LANG_ID}\"" "$ADAPTERS_FILE"; then
  update_file_with_awk "$ADAPTERS_FILE" \
    -v insert_line="    ${EXT_EXPR} \"${LANG_ID}\"" '
      BEGIN { inserted=0 }
      /^    :else nil\)\)$/ && inserted==0 { print insert_line; inserted=1 }
      { print }
    '
else
  log "skip language-by-path mapping, appears present for: $LANG_ID"
fi

if ! grep -q "(defn- parse-${LANG_ID} " "$ADAPTERS_FILE"; then
  PARSER_STUB="$(cat <<EOF
(defn- parse-${LANG_ID} [path lines]
  {:language "${LANG_ID}"
   :module nil
   :imports []
   :units []
   :diagnostics [{:code "parser_stub"
                  :summary "${LANG_TITLE} adapter scaffold generated by scripts/new-language-adapter.sh; implement parser extraction."}]
   :parser_mode "fallback"})

EOF
)"
  if [[ "$DRY_RUN" == "true" ]]; then
    log "[dry-run] patch: $ADAPTERS_FILE"
  else
    block_file="$(mktemp)"
    tmp_out="$(mktemp)"
    printf '%s' "$PARSER_STUB" > "$block_file"
    awk -v block_file="$block_file" '
      BEGIN {
        inserted=0
        while ((getline line < block_file) > 0) {
          block = block line ORS
        }
        close(block_file)
      }
      /^\(defn- fallback-unit / && inserted==0 { printf "%s", block; inserted=1 }
      { print }
    ' "$ADAPTERS_FILE" > "$tmp_out"
    mv "$tmp_out" "$ADAPTERS_FILE"
    rm -f "$block_file"
    log "patched: $ADAPTERS_FILE"
  fi
else
  log "skip parse stub, function already exists: parse-${LANG_ID}"
fi

if ! grep -q "\"${LANG_ID}\" (parse-${LANG_ID} file-path lines)" "$ADAPTERS_FILE"; then
  update_file_with_awk "$ADAPTERS_FILE" \
    -v insert_line="           \"${LANG_ID}\" (parse-${LANG_ID} file-path lines)" '
      BEGIN { inserted=0 }
      /\(fallback-unit file-path lines language "unsupported_language"\)/ && inserted==0 {
        print insert_line
        inserted=1
      }
      { print }
    '
else
  log "skip parse-file branch, appears present: $LANG_ID"
fi

TEST_CONTENT="$(cat <<EOF
(ns semidx.${LANG_NS}-onboarding-test
  (:require [clojure.test :refer [deftest is]]))

(deftest ${LANG_ID}-adapter-onboarding-scaffold-test
  (is true "${LANG_TITLE} onboarding scaffold test. Replace with real parser/retrieval assertions."))
EOF
)"
write_file "$TEST_FILE" "$TEST_CONTENT"

if ! grep -q "semidx.${LANG_NS}-onboarding-test" "$TEST_RUNNER_FILE"; then
  update_file_with_awk "$TEST_RUNNER_FILE" \
    -v require_line="            [semidx.${LANG_NS}-onboarding-test]" '
      BEGIN { inserted=0 }
      /^[[:space:]]*\[semidx\.runtime-test\]\)\)$/ && inserted==0 {
        print require_line
        inserted=1
      }
      { print }
    '
else
  log "skip test-runner require, appears present: semidx.${LANG_NS}-onboarding-test"
fi

if ! grep -q "'semidx.${LANG_NS}-onboarding-test" "$TEST_RUNNER_FILE"; then
  update_file_with_awk "$TEST_RUNNER_FILE" \
    -v test_line="                            'semidx.${LANG_NS}-onboarding-test" '
      BEGIN { inserted=0 }
      index($0, "'\''semidx.runtime-http-test)") > 0 && inserted==0 {
        sub(/\)$/, "")
        print
        print test_line ")"
        inserted=1
        next
      }
      { print }
    '
else
  log "skip test-runner run-tests entry, appears present: semidx.${LANG_NS}-onboarding-test"
fi

FIXTURE_HAPPY_CONTENT="$(cat <<EOF
{
  "fixture_id": "retrieval_${LANG_ID}_happy_path_001",
  "category": "${LANG_ID}_onboarding",
  "purpose": "${LANG_TITLE} onboarding fixture scaffold (replace with real expectation assertions).",
  "adr_refs": ["ADR-014", "ADR-022"],
  "snapshot_ref": "seed-polyglot-app@rev-scaffold",
  "input": {
    "query": {
      "api_version": "1.0",
      "schema_version": "1.0",
      "intent": {
        "purpose": "code_understanding",
        "details": "Scaffold query for ${LANG_TITLE} language adapter onboarding."
      },
      "targets": {
        "paths": ["src/example/main.${PRIMARY_EXT_NO_DOT}"]
      },
      "constraints": {
        "token_budget": 1200,
        "language_allowlist": ["${LANG_ID}"],
        "max_raw_code_level": "enclosing_unit",
        "freshness": "current_snapshot"
      },
      "hints": {
        "prefer_definitions_over_callers": true
      },
      "options": {
        "include_tests": false,
        "include_impact_hints": true,
        "allow_raw_code_escalation": false
      },
      "trace": {
        "trace_id": "11111111-2222-4333-8444-555555555555",
        "request_id": "fixture-${LANG_ID}-happy-path-001"
      }
    }
  },
  "expected": {}
}
EOF
)"
write_file "$FIXTURE_HAPPY" "$FIXTURE_HAPPY_CONTENT"

FIXTURE_AMBIG_CONTENT="$(cat <<EOF
{
  "fixture_id": "retrieval_${LANG_ID}_ambiguity_001",
  "category": "${LANG_ID}_ambiguity",
  "purpose": "${LANG_TITLE} ambiguity fixture scaffold (replace with confidence and warning expectations).",
  "adr_refs": ["ADR-005", "ADR-008", "ADR-014", "ADR-022"],
  "snapshot_ref": "seed-polyglot-app@rev-scaffold",
  "input": {
    "query": {
      "api_version": "1.0",
      "schema_version": "1.0",
      "intent": {
        "purpose": "bug_investigation",
        "details": "Scaffold ambiguity investigation query for ${LANG_TITLE} adapter."
      },
      "targets": {
        "paths": ["src/example/main.${PRIMARY_EXT_NO_DOT}", "test/example/main_test.${PRIMARY_EXT_NO_DOT}"],
        "diff_summary": "Scaffold diff for ${LANG_TITLE} onboarding."
      },
      "constraints": {
        "token_budget": 1400,
        "language_allowlist": ["${LANG_ID}"],
        "max_raw_code_level": "enclosing_unit",
        "freshness": "current_snapshot"
      },
      "hints": {
        "prefer_definitions_over_callers": false,
        "prefer_breadth_over_depth": true
      },
      "options": {
        "include_tests": true,
        "include_impact_hints": true,
        "allow_raw_code_escalation": false
      },
      "trace": {
        "trace_id": "66666666-7777-4888-8999-000000000000",
        "request_id": "fixture-${LANG_ID}-ambiguity-001"
      }
    }
  },
  "expected": {}
}
EOF
)"
write_file "$FIXTURE_AMBIG" "$FIXTURE_AMBIG_CONTENT"

DOC_CONTENT="$(cat <<EOF
# ${LANG_TITLE} Onboarding Scaffold

Generated by \`scripts/new-language-adapter.sh\`.

## Current State

- Language key: \`${LANG_ID}\`
- File extensions: \`${EXT_CSV}\`
- Parser function scaffold: \`parse-${LANG_ID}\`
- Fixture files:
  - \`${FIXTURE_HAPPY}\`
  - \`${FIXTURE_AMBIG}\`

## Next Steps (ADR-022)

1. Implement parser extraction logic in \`runtime/adapters.clj\`.
2. Replace onboarding test scaffold with real retrieval assertions.
3. Replace empty fixture \`expected\` blocks with meaningful checks.
4. Run \`./scripts/validate-language-onboarding.sh ${LANG_ID}\`.
EOF
)"
write_file "$DOC_ONBOARDING" "$DOC_CONTENT"

if [[ "$DRY_RUN" == "false" ]]; then
  LANG_ID="$LANG_ID" \
  FIXTURE_HAPPY_FILE="$(basename "$FIXTURE_HAPPY")" \
  FIXTURE_AMBIG_FILE="$(basename "$FIXTURE_AMBIG")" \
  CORPUS_FILE="$CORPUS_FILE" \
  clojure -M -e '
    (require '\''[clojure.data.json :as json]
             '\''[clojure.java.io :as io])
    (let [lang-id (System/getenv "LANG_ID")
          fixture-happy (System/getenv "FIXTURE_HAPPY_FILE")
          fixture-ambig (System/getenv "FIXTURE_AMBIG_FILE")
          corpus-file (System/getenv "CORPUS_FILE")
          corpus (with-open [r (io/reader corpus-file)]
                   (json/read r :key-fn keyword))
          existing (set (map :fixture_id (:fixtures corpus)))
          mk (fn [fixture-id category path purpose]
               {:fixture_id fixture-id
                :category category
                :path path
                :purpose purpose})
          additions (cond-> []
                      (not (contains? existing (str "retrieval_" lang-id "_happy_path_001")))
                      (conj (mk (str "retrieval_" lang-id "_happy_path_001")
                                (str lang-id "_onboarding")
                                fixture-happy
                                (str "Scaffold fixture for " lang-id " language onboarding (replace with real assertions).")))
                      (not (contains? existing (str "retrieval_" lang-id "_ambiguity_001")))
                      (conj (mk (str "retrieval_" lang-id "_ambiguity_001")
                                (str lang-id "_ambiguity")
                                fixture-ambig
                                (str "Scaffold ambiguity fixture for " lang-id " language onboarding (replace with real assertions)."))))
          updated (if (seq additions)
                    (update corpus :fixtures into additions)
                    corpus)]
      (when (seq additions)
        (with-open [w (io/writer corpus-file)]
          (json/write updated w :indent true :escape-slash false)))
      (println (str "corpus_additions=" (count additions))))'
else
  log "[dry-run] update corpus: $CORPUS_FILE"
fi

log "done: language onboarding scaffold generated for '$LANG_ID'"
log "next: ./scripts/validate-language-onboarding.sh $LANG_ID --skip-gates"
